<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>cn.geoair.geo.dynamic</groupId>
        <artifactId>geoair-dynamic</artifactId>
        <version>23.1.2-RC3-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <groupId>cn.geoair.geo.dynamic</groupId>
    <version>23.1.2-RC3-SNAPSHOT</version>
    <artifactId>geo-dynamic-geoserver</artifactId>
    <name>geo-dynamic-geoserver</name>

    <properties>
        <java.version>8</java.version>
        <geoair.version>23.1.2-RC3-SNAPSHOT</geoair.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <geotools.version>28.6.1</geotools.version>
        <geoserver.version>2.22.6</geoserver.version>
    </properties>

    <description>geo-dynamic-geoserver</description>

    <url>https://gitee.com/geoair/geo-dynamic</url>

    <licenses>
        <license>
            <name>The Apache Software License, cn.geoair.map.dynamic.tools.Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
        </license>
    </licenses>

    <developers>
        <developer>
            <name>zhangfengji</name>
            <email>1159856928@qq.com</email>
            <organization>geoair</organization>
            <organizationUrl>https://xmt.geoair.cn/</organizationUrl>
        </developer>
    </developers>

    <scm>
        <connection>https://gitee.com/geoair/geo-dynamic.git</connection>
        <developerConnection>scm:git:ssh://git@gitee.com:geoair/geo-dynamic.git</developerConnection>
        <url>https://gitee.com/geoair/geo-dynamic</url>
    </scm>


    <dependencies>
        <dependency>
            <groupId>org.geoserver</groupId>
            <artifactId>gs-main</artifactId>
            <version>${geoserver.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>javax.servlet</groupId>
                    <artifactId>servlet-api</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.springframework</groupId>
                    <artifactId>spring-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.geoserver</groupId>
            <artifactId>gs-wms</artifactId>
            <version>${geoserver.version}</version>
        </dependency>
        <dependency>
            <groupId>org.geoserver</groupId>
            <artifactId>gs-wfs</artifactId>
            <version>${geoserver.version}</version>
        </dependency>
        <dependency>
            <groupId>org.geoserver</groupId>
            <artifactId>gs-jdbc-postgis</artifactId>
            <version>${geoserver.version}</version>
        </dependency>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>${postgresql.version}</version>
        </dependency>
        <!-- GeoTools 核心 -->
        <dependency>
            <groupId>org.geotools</groupId>
            <artifactId>gt-main</artifactId>
            <version>${geotools.version}</version>
        </dependency>

        <!-- Spring Boot 配置处理器（可选） -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>8</source>
                    <target>8</target>
                    <encoding>UTF-8</encoding>
                </configuration>
            </plugin>

        </plugins>
    </build>

    <repositories>
        <repository>
            <id>osgeo</id>
            <name>OSGeo Release Repository</name>
            <url>https://repo.osgeo.org/repository/release/</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>geotools</id>
            <name>GeoTools Repository</name>
            <url>https://repo.osgeo.org/repository/geotools/</url>
        </repository>
    </repositories>


</project>
