<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>cn.geoair.devkit</groupId>
    <artifactId>geoair-apidoc</artifactId>
    <version>J17.1.6</version>
    <relativePath>../pom.xml</relativePath>
  </parent>
  <groupId>cn.geoair.devkit</groupId>
  <artifactId>geoair-knife4j-springfox-spring-boot-starter</artifactId>
  <version>J17.1.6</version>
  <packaging>jar</packaging>
  <name>geoair-knife4j-springfox-spring-boot-starter</name>

  <description>geoair-knife4j-springfox-spring-boot-starter</description>

  <url>https://github.com/geoair-cn/geoair</url>

  <licenses>
    <license>
      <name>The Apache Software License, Version 2.0</name>
      <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
    </license>
  </licenses>

  <developers>
    <developer>
      <name>zhangfengji</name>
      <email>zfj20250104@qq.com</email>
      <organization>geoair</organization>
      <organizationUrl>https://xmt.geoair.cn/</organizationUrl>
    </developer>
  </developers>

  <scm>
    <connection>scm:git://github.com/geoair-cn/geoair.git</connection>
    <developerConnection>scm:git:https://github.com:geoair-cn/geoair.git</developerConnection>
    <tag>HEAD</tag>
    <url>https://github.com/geoair-cn/geoair</url>
  </scm>

  <properties>

  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>io.springfox</groupId>
        <artifactId>springfox-spring-web</artifactId>
        <version>${springfox.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <dependency>
      <groupId>cn.geoair.devkit</groupId>
      <artifactId>geoair-web</artifactId>
      <version>${geoair.version}</version>
    </dependency>

    <dependency>
      <groupId>cn.geoair.devkit</groupId>
      <artifactId>geoair-core</artifactId>
      <version>${geoair.version}</version>
    </dependency>

    <dependency>
      <groupId>io.springfox</groupId>
      <artifactId>springfox-spring-web</artifactId>
      <version>${springfox.version}</version>
      <scope>compile</scope>
    </dependency>

    <dependency>
      <groupId>com.github.xiaoymin</groupId>
      <artifactId>knife4j-spring-boot-starter</artifactId>
      <version>${knife4j.openapi2.version}</version>
      <exclusions>
        <exclusion>
          <artifactId>springfox-spring-web</artifactId>
          <groupId>io.springfox</groupId>
        </exclusion>
      </exclusions>
    </dependency>

    <dependency>
      <groupId>cn.geoair.devkit</groupId>
      <artifactId>geoair-knife4j-core</artifactId>
      <version>${geoair.version}</version>
      <scope>compile</scope>
    </dependency>

    <dependency>
      <groupId>io.springfox</groupId>
      <artifactId>springfox-swagger2</artifactId>
      <version>${springfox.version}</version>
      <scope>compile</scope>
    </dependency>

    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-webmvc</artifactId>
      <version>${spring.version}</version>
    </dependency>

    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
      <version>${jackson.version.databind}</version>
      <optional>false</optional>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-configuration-processor</artifactId>
      <version>${spring-boot.version}</version>
      <optional>true</optional>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-aop</artifactId>
      <version>${spring-boot.version}</version>
    </dependency>

    <dependency>
      <groupId>org.reflections</groupId>
      <artifactId>reflections</artifactId>
      <version>${reflections.version}</version>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-actuator-autoconfigure</artifactId>
      <version>${spring-boot.version}</version>
      <optional>true</optional>
    </dependency>

    <dependency>
      <groupId>cn.hutool</groupId>
      <artifactId>hutool-all</artifactId>
      <version>${hutool.version}</version>
    </dependency>

  </dependencies>

</project>
