<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>cn.geoair.devkit</groupId>
    <artifactId>geoair-standard</artifactId>
    <version>J8-dev-SNAPSHOT</version>
    <relativePath>../pom.xml</relativePath>
  </parent>
  <groupId>cn.geoair.devkit</groupId>
  <artifactId>geoair-orm</artifactId>
  <version>J8-dev-SNAPSHOT</version>
  <packaging>pom</packaging>
  <name>geoair-orm</name>
  <description>geoair-orm</description>
  <url>https://github.com/geoair-cn/geoair</url>

  <licenses>
    <license>
      <name>The Apache Software License, Version 2.0</name>
      <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
    </license>
  </licenses>

  <developers>
    <developer>
      <name>zhangfengji</name>
      <email>1159856928@qq.com</email>
      <organization>geoair</organization>
      <organizationUrl>https://xmt.geoair.cn/</organizationUrl>
    </developer>
  </developers>

  <modules>

    <module>geoair-orm-mybatis</module>
    <module>geoair-orm-mybatis-tk</module>
    <module>geoair-orm-mybatis-plus</module>
    <module>geoair-orm-springjpa</module>
    <module>geoair-orm-spi</module>
    <module>geoair-orm-base</module>
  </modules>

  <scm>
    <connection>scm:git://github.com/geoair-cn/geoair.git</connection>
    <developerConnection>scm:git:https://github.com:geoair-cn/geoair.git</developerConnection>
    <tag>HEAD</tag>
    <url>https://github.com/geoair-cn/geoair</url>
  </scm>
  <dependencyManagement>
    <dependencies>
      <!--            <dependency>-->
      <!--               <groupId>cn.geoair.devkit</groupId>-->
      <!--                <artifactId>geoair-mybatis</artifactId>-->
      <!--            </dependency>-->

    </dependencies>
  </dependencyManagement>

</project>
