<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>cn.geoair.dependencies</groupId>
        <artifactId>geoair-base-parent</artifactId>
        <version>23.1.1-bata4-SNAPSHOT</version>
        <relativePath>../geoair-base-parent</relativePath>
    </parent>

    <groupId>cn.geoair.comp</groupId>
    <artifactId>geoair-comp</artifactId>
    <packaging>pom</packaging>
    <name>geoair-comp</name>


    <properties>
        <skipTests>true</skipTests>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>cn.geoair</groupId>
                <artifactId>geoair</artifactId>
                <version>${geoair.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>cn.geoair.comp.apidoc</groupId>
                <artifactId>geoair-knife4j-spring-boot-starter</artifactId>
                <version>${geoair.version}</version>
            </dependency>

        </dependencies>
    </dependencyManagement>

    <modules>
        <module>geoair-apidoc</module>

    </modules>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>
