<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-dependencies</artifactId>
        <version>2.7.18</version>
        <relativePath/>
    </parent>
   <groupId>cn.geoair.eight</groupId>
    <artifactId>geoair-base-dependencies-parent</artifactId>
    <version>J8.1.0-SNAPSHOT</version>
    <name>geoair-base-dependencies-parent</name>
    <packaging>pom</packaging>
    <description>用于定义各个组件的依赖管理</description>

    <properties>
        <skipTests>true</skipTests>
        <geoair.version>J8.1.0-SNAPSHOT</geoair.version>
        <java.version>8</java.version>
        <okhttp.version>4.12.0</okhttp.version>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <maven.build.timestamp.format>yyyy-MM-dd-HH-mm-ss</maven.build.timestamp.format>
        <versions-maven-release.version>3.1.0</versions-maven-release.version>
        <redisson.version>3.23.5</redisson.version>
        <sa-token-version>1.44.0</sa-token-version>
        <tomcat.version>9.0.115</tomcat.version>
        <spring-boot.version>2.7.18</spring-boot.version>
        <fastjson.version>2.0.43</fastjson.version>
        <dom4j.version>1.6.1</dom4j.version>


        <!--        <mapstruct.version>1.4.2.Final</mapstruct.version>-->
        <mapstruct.version>1.5.5.Final</mapstruct.version>


        <net.postgis.version>2025.1.1</net.postgis.version>
        <org.postgis.version>1.3.3</org.postgis.version>
        <druid.version>1.2.23</druid.version>
        <mapper-module.version>4.2.0</mapper-module.version>
        <geotools.version>28.6.1</geotools.version>
        <geoserver.version>2.22.6</geoserver.version>
        <mybatis-plus.version>3.5.2</mybatis-plus.version>
        <hutool.version>5.8.42</hutool.version>
        <jts.version>1.19.0</jts.version>
        <ecc.vectortile.version>1.3.9</ecc.vectortile.version>
        <proj4j.version>1.3.0</proj4j.version>
        <spring-javaformat.version>0.0.28</spring-javaformat.version>


        <spring.version>5.3.31</spring.version>
        <reflections.version>0.10.2</reflections.version>
        <mybatis.version>3.5.9</mybatis.version>
        <mybatis-spring.version>2.0.7</mybatis-spring.version>
        <pagehelper.version>5.3.2</pagehelper.version>
        <lombok.version>1.18.30</lombok.version>
        <fastjson1x.version>1.2.83</fastjson1x.version>
        <jackson.version>2.13.5</jackson.version>
        <gson.version>2.9.1</gson.version>
        <javax-persistence.version>2.2</javax-persistence.version>
        <javax-cache.version>1.1.1</javax-cache.version>
        <javax-annotation.version>1.3.2</javax-annotation.version>

        <!-- Jackson 子版本（基于统一的jackson.version） -->
        <jackson.version.annotations>${jackson.version}</jackson.version.annotations>
        <jackson.version.core>${jackson.version}</jackson.version.core>
        <jackson.version.databind>${jackson.version}</jackson.version.databind>
        <jackson.version.dataformat>${jackson.version}</jackson.version.dataformat>
        <jackson.version.datatype>${jackson.version}</jackson.version.datatype>
        <jackson.version.jaxrs>${jackson.version}</jackson.version.jaxrs>
        <jackson.version.jakarta.rs>${jackson.version}</jackson.version.jakarta.rs>
        <jackson.version.jacksonjr>${jackson.version}</jackson.version.jacksonjr>

        <postgresql.version>42.3.8</postgresql.version>
        <jedis.version>3.8.0</jedis.version>
        <hibernate.version>5.6.15.Final</hibernate.version>
        <maven-jar-plugin.version>3.2.2</maven-jar-plugin.version>
        <servlet-api.version>4.0.1</servlet-api.version>


        <springfox.version>3.0.0</springfox.version>
        <springdoc.version>1.7.0</springdoc.version>
        <knife4j-openapi3.version>4.4.0</knife4j-openapi3.version>
        <knife4j.openapi2.version>3.0.3</knife4j.openapi2.version>

        <maven-compiler-plugin.version>3.10.1</maven-compiler-plugin.version>
        <versions-maven-plugin.version>2.7</versions-maven-plugin.version>
        <maven-source-plugin.version>3.2.1</maven-source-plugin.version>
        <maven-javadoc-plugin.version>3.4.1</maven-javadoc-plugin.version>
    </properties>
    <url>https://gitee.com/geoair/geoair</url>

    <licenses>
        <license>
            <name>The Apache Software License, Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
        </license>
    </licenses>

    <developers>
        <developer>
            <name>张逢吉</name>
            <email>1159856928@qq.com</email>
            <organization>geoair</organization>
            <organizationUrl>https://xmt.geoair.cn/</organizationUrl>
        </developer>
    </developers>

    <scm>
        <connection>scm:git:git://gitee.com/geoair/geoair.git</connection>
        <developerConnection>scm:git:git@gitee.com:geoair/geoair.git</developerConnection>
        <url>https://gitee.com/geoair/geoair</url>
        <tag>HEAD</tag>
    </scm>

    <dependencyManagement>
        <dependencies>

            <dependency>
               <groupId>cn.geoair.eight</groupId>
                <artifactId>geoair-base-dependencies-geotools</artifactId>
                <version>${geoair.version}</version>

            </dependency>
            <dependency>
               <groupId>cn.geoair.eight</groupId>
                <artifactId>geoair-base-dependencies-swagger</artifactId>
                <version>${geoair.version}</version>

            </dependency>
            <dependency>
               <groupId>cn.geoair.eight</groupId>
                <artifactId>geoair-base-dependencies-spring</artifactId>
                <version>${geoair.version}</version>

            </dependency>
            <dependency>
               <groupId>cn.geoair.eight</groupId>
                <artifactId>geoair-base-dependencies-template</artifactId>
                <version>${geoair.version}</version>

            </dependency>

            <dependency>
               <groupId>cn.geoair.eight</groupId>
                <artifactId>geoair-base-dependencies-other</artifactId>
                <version>${geoair.version}</version>

            </dependency>

        </dependencies>
    </dependencyManagement>


    <modules>
        <module>geoair-base-dependencies-geotools</module>
        <module>geoair-base-dependencies-swagger</module>
        <module>geoair-base-dependencies-spring</module>
        <module>geoair-base-dependencies-template</module>
        <module>geoair-base-dependencies-other</module>
    </modules>


    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-source-plugin</artifactId>
                    <version>${maven-source-plugin.version}</version>
                    <configuration>
                        <attach>true</attach>
                    </configuration>
                    <executions>
                        <execution>
                            <phase>compile</phase>
                            <goals>
                                <goal>jar</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${maven-compiler-plugin.version}</version>
                    <configuration>
                        <parameters>true</parameters>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-javadoc-plugin</artifactId>
                    <version>${maven-javadoc-plugin.version}</version>
                    <executions>
                        <execution>
                            <id>attach-javadocs</id>
                            <goals>
                                <goal>jar</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-gpg-plugin</artifactId>
                    <version>1.5</version>
                    <executions>
                        <execution>
                            <id>sign-artifacts</id>
                            <phase>verify</phase>
                            <goals>
                                <goal>sign</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.sonatype.central</groupId>
                    <artifactId>central-publishing-maven-plugin</artifactId>
                    <version>0.9.0</version>
                    <extensions>true</extensions>
                    <configuration>
                        <publishingServerId>central</publishingServerId>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>

        <plugins>


            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-release-plugin</artifactId>
                <version>${versions-maven-release.version}</version>
                <configuration>
                    <!-- 跳过自动提交（如需手动确认可关闭） -->
                    <autoVersionSubmodules>true</autoVersionSubmodules>
                    <!-- 避免重复提交标签 -->
                    <tagNameFormat>${project.artifactId}-${project.version}</tagNameFormat>
                    <!-- 发布后自动推送到远程仓库 -->
                    <pushChanges>true</pushChanges>
                    <branchName>master</branchName>

                    <!--                    <threadSafe>true</threadSafe>-->
                    <!--                    &lt;!&ndash; 核心：跳过从 SCM 检出代码，直接用本地代码 &ndash;&gt;-->
                    <!--                    <checkoutReleaseBranch>false</checkoutReleaseBranch>-->
                    <!--                    &lt;!&ndash; 强制指定 SCM 地址 &ndash;&gt;-->
                    <!--                    <scmUrl>scm:git:git://gitee.com/geoair/geoair.git</scmUrl>-->

                </configuration>
            </plugin>

            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>versions-maven-plugin</artifactId>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>${maven-jar-plugin.version}</version>
                <configuration>
                    <!--					<classifier>bak</classifier>-->
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven-compiler-plugin.version}</version>
                <configuration>
                    <!-- 源码版本 -->
                    <source>8</source>
                    <!-- 目标字节码版本 -->
                    <target>8</target>
                    <!-- 编码（可选，避免中文乱码） -->
                    <encoding>UTF-8</encoding>
                </configuration>
            </plugin>

            <!--生成源码插件-->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <goals>
                            <goal>jar-no-fork</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <!--生成API文档插件-->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <configuration>
                    <encoding>UTF-8</encoding>
                    <failOnError>false</failOnError> <!-- 忽略错误，继续执行 -->
                </configuration>
                <executions>
                    <execution>
                        <id>attach-javadocs</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>central</id>
            <distributionManagement>
                <snapshotRepository>
                    <id>ossrh</id>
                    <url>https://central.sonatype.com/repository/maven-snapshots/</url>
                </snapshotRepository>
                <repository>
                    <id>ossrh</id>
                    <url>https://central.sonatype.com/repository/maven-snapshots/</url>
                </repository>
            </distributionManagement>
            <build>
                <!--发布到中央SNAPSHOT仓库插件-->
                <plugins>
                    <!--gpg插件-->
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-gpg-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>sign-artifacts</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>sign</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.sonatype.central</groupId>
                        <artifactId>central-publishing-maven-plugin</artifactId>
                        <version>0.9.0</version>
                        <extensions>true</extensions>
                        <configuration>
                            <publishingServerId>central</publishingServerId>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <profile>
            <id>javaformat</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>io.spring.javaformat</groupId>
                        <artifactId>spring-javaformat-maven-plugin</artifactId>
                        <version>${spring-javaformat.version}</version>
                        <executions>
                            <execution>
                                <phase>validate</phase>
                                <goals>
                                    <goal>validate</goal>
                                </goals>
                                <inherited>true</inherited>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>


        <profile>
            <id>geoair-group-repo</id>
            <distributionManagement>
                <repository>
                    <id>gir-release</id>
                    <url>http://xmt.geoair.cn:32000/repository/109-release/</url>
                </repository>
                <snapshotRepository>
                    <id>gir-snapshot</id>
                    <url>http://xmt.geoair.cn:32000/repository/109-snapshot/</url>
                </snapshotRepository>
            </distributionManagement>
        </profile>
    </profiles>

</project>
