<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>cn.geoair.devkit</groupId>
    <artifactId>geoair-framework</artifactId>
    <version>J17-dev-SNAPSHOT</version>
    <relativePath>../pom.xml</relativePath>
  </parent>
  <groupId>cn.geoair.devkit</groupId>
  <artifactId>geoair-base-parent</artifactId>
  <version>J17-dev-SNAPSHOT</version>
  <packaging>pom</packaging>
  <name>geoair-base-parent</name>
  <description>geoair base parent 用于Gir基础库的依赖约束</description>

  <url>https://github.com/geoair-cn/geoair</url>

  <licenses>
    <license>
      <name>The Apache Software License, Version 2.0</name>
      <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
    </license>
  </licenses>

  <developers>
    <developer>
      <name>张逢吉</name>
      <email>zfj20250104@qq.com</email>
      <organization>geoair</organization>
      <organizationUrl>https://xmt.geoair.cn/</organizationUrl>
    </developer>
  </developers>

  <scm>
    <connection>scm:git://github.com/geoair-cn/geoair.git</connection>
    <developerConnection>scm:git:https://github.com:geoair-cn/geoair.git</developerConnection>
    <tag>HEAD</tag>
    <url>https://github.com/geoair-cn/geoair</url>
  </scm>

  <properties>


    <geoair.version>J17-dev-SNAPSHOT</geoair.version>
    <slf4j.version>1.7.36</slf4j.version>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>cn.geoair.devkit</groupId>
        <artifactId>geoair-framework</artifactId>
        <version>${geoair.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>cn.geoair.devkit</groupId>
        <artifactId>geoair-spring-dependencies</artifactId>
        <version>${geoair.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-dependencies</artifactId>
        <version>${spring-boot.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>cn.geoair.devkit</groupId>
        <artifactId>geoair-common-dependencies</artifactId>
        <version>${geoair.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>

      <dependency>
        <groupId>cn.geoair.devkit</groupId>
        <artifactId>geoair-geotools-dependencies</artifactId>
        <version>${geoair.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>cn.geoair.devkit</groupId>
        <artifactId>geoair-openapi-dependencies</artifactId>
        <version>${geoair.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>

    </dependencies>
  </dependencyManagement>

  <build>


  </build>

</project>
