<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>cn.geoair.devkit</groupId>
    <artifactId>geoair-file-tran</artifactId>
    <version>J8-dev-SNAPSHOT</version>
    <relativePath>../pom.xml</relativePath>
  </parent>
  <groupId>cn.geoair.devkit</groupId>
  <artifactId>geoair-file-test</artifactId>
  <version>J8-dev-SNAPSHOT</version>
  <packaging>jar</packaging>
  <name>geoair-file-test</name>

  <description>geoair-file-tran
        转换测试模块</description>

  <url>https://github.com/geoair-cn/geoair</url>

  <licenses>
    <license>
      <name>The Apache Software License, cn.geoair.map.dynamic.tools.Version 2.0</name>
      <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
    </license>
  </licenses>

  <developers>
    <developer>
      <name>zhangfengji</name>
      <email>1159856928@qq.com</email>
      <organization>geoair</organization>
      <organizationUrl>https://xmt.geoair.cn/</organizationUrl>
    </developer>
  </developers>

  <scm>
    <connection>https://github.com/geoair-cn/geoair.git</connection>
    <developerConnection>scm:git:https://github.com:geoair-cn/geoair.git</developerConnection>
    <url>https://github.com/geoair-cn/geoair</url>
  </scm>
  <properties>
    <java.version>8</java.version>
    <geoair.version>J8-dev-SNAPSHOT</geoair.version>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <maven.deploy.skip>true</maven.deploy.skip>
    <maven.install.skip>true</maven.install.skip>
  </properties>

  <dependencies>

    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <version>${lombok.version}</version>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.geotools</groupId>
      <artifactId>gt-referencing</artifactId>
      <version>${geotools.version}</version>
    </dependency>
    <dependency>
      <groupId>cn.geoair.devkit</groupId>
      <artifactId>geoair-file-geojson</artifactId>
      <version>${geoair.version}</version>
    </dependency>
    <dependency>
      <groupId>cn.geoair.devkit</groupId>
      <artifactId>geoair-file-shp</artifactId>
      <version>${geoair.version}</version>
    </dependency>
    <dependency>
      <groupId>cn.geoair.devkit</groupId>
      <artifactId>geoair-file-postgis</artifactId>
      <version>${geoair.version}</version>
    </dependency>

  </dependencies>

  <build>
    <plugins>


    </plugins>
  </build>

</project>
