<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>cn.geoair.devkit</groupId>
    <artifactId>geoair-framework</artifactId>
    <version>J17-dev-SNAPSHOT</version>
    <relativePath>../pom.xml</relativePath>
  </parent>
  <groupId>cn.geoair.devkit</groupId>
  <artifactId>geoair-framework-bom</artifactId>
  <version>J17-dev-SNAPSHOT</version>
  <packaging>pom</packaging>
  <name>geoair-framework-bom</name>
  <description>用于工程模块的依赖定义</description>

  <url>https://github.com/geoair-cn/geoair</url>

  <licenses>
    <license>
      <name>The Apache Software License, Version 2.0</name>
      <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
    </license>
  </licenses>

  <developers>
    <developer>
      <name>张逢吉</name>
      <email>1159856928@qq.com</email>
      <organization>geoair</organization>
      <organizationUrl>https://xmt.geoair.cn/</organizationUrl>
    </developer>
  </developers>

  <!--    <dependencies>-->
  <!--        <dependency>-->
  <!--           <groupId>cn.geoair.devkit</groupId>-->
  <!--            <artifactId>geoair-base-parent</artifactId>-->
  <!--            <version>${geoair.version}</version>-->
  <!--            <type>pom</type>-->
  <!--        </dependency>-->
  <!--    </dependencies>-->

  <modules>
    <module>geoair-api-parent</module>
    <module>geoair-project-parent</module>
    <module>geoair-spring-boot-starter-parent</module>
  </modules>

  <scm>
    <connection>scm:git://github.com/geoair-cn/geoair.git</connection>
    <developerConnection>scm:git:https://github.com:geoair-cn/geoair.git</developerConnection>
    <tag>HEAD</tag>
    <url>https://github.com/geoair-cn/geoair</url>
  </scm>

  <properties>
    <!--        <geoair.version>J17-dev-SNAPSHOT</geoair.version>-->
    <!--        <geoair.comp.version>J17-dev-SNAPSHOT</geoair.comp.version>-->

    <skipTests>true</skipTests>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>cn.geoair.devkit</groupId>
        <artifactId>geoair-base-parent</artifactId>
        <version>${geoair.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <build>
    <pluginManagement>
      <plugins>

        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-gpg-plugin</artifactId>
          <version>1.5</version>
          <executions>
            <execution>
              <id>sign-artifacts</id>
              <phase>verify</phase>
              <goals>
                <goal>sign</goal>
              </goals>
            </execution>
          </executions>
        </plugin>
        <plugin>
          <groupId>org.sonatype.central</groupId>
          <artifactId>central-publishing-maven-plugin</artifactId>
          <version>0.9.0</version>
          <extensions>true</extensions>
          <configuration>
            <publishingServerId>central</publishingServerId>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>

</project>
