<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>cn.geoair.devkit</groupId>
    <artifactId>geoair-base-parent</artifactId>
    <version>J17-dev-SNAPSHOT</version>
    <relativePath>../geoair-base-parent</relativePath>
  </parent>

  <groupId>cn.geoair.devkit</groupId>
  <artifactId>geoair-modules</artifactId>
  <version>J17-dev-SNAPSHOT</version>
  <packaging>pom</packaging>
  <name>geoair-modules</name>

  <description>geoair 组件库</description>

  <url>https://github.com/geoair-cn/geoair</url>

  <licenses>
    <license>
      <name>The Apache Software License, Version 2.0</name>
      <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
    </license>
  </licenses>

  <developers>
    <developer>
      <name>zhangfengji</name>
      <email>1159856928@qq.com</email>
      <organization>geoair</organization>
      <organizationUrl>https://xmt.geoair.cn/</organizationUrl>
    </developer>
  </developers>

  <modules>
    <module>geoair-apidoc</module>
    <module>geoair-code-generator</module>
    <module>geoair-geo</module>
    <module>geoair-dynamic-ds</module>
    <module>geoair-db-service</module>
    <module>geoair-message-jts-jackson</module>
    <module>geoair-message-jts-mybatis</module>
    <module>geoair-official-site</module>

  </modules>

  <scm>
    <connection>scm:git://github.com/geoair-cn/geoair.git</connection>
    <developerConnection>scm:git:https://github.com:geoair-cn/geoair.git</developerConnection>
    <tag>HEAD</tag>
    <url>https://github.com/geoair-cn/geoair</url>
  </scm>

  <properties>
    <skipTests>true</skipTests>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>cn.geoair.devkit</groupId>
        <artifactId>geoair-standard</artifactId>
        <version>${geoair.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>


      <dependency>
        <groupId>cn.geoair.devkit</groupId>
        <artifactId>geoair-knife4j-springdoc-spring-boot-starter</artifactId>
        <version>${geoair.version}</version>
      </dependency>

      <dependency>
        <groupId>cn.geoair.devkit</groupId>
        <artifactId>geoair-code-gen-module</artifactId>
        <version>${geoair.version}</version>
      </dependency>
      <dependency>
        <groupId>cn.geoair.devkit</groupId>
        <artifactId>geoair-message-jts-jackson</artifactId>
        <version>${geoair.version}</version>
      </dependency>
      <dependency>
        <groupId>cn.geoair.devkit</groupId>
        <artifactId>geoair-message-jts-mybatis</artifactId>
        <version>${geoair.version}</version>
      </dependency>
      <dependency>
        <groupId>cn.geoair.devkit</groupId>
        <artifactId>geoair-db-service-core</artifactId>
        <version>${geoair.version}</version>
      </dependency>
      <dependency>
        <groupId>cn.geoair.devkit</groupId>
        <artifactId>geoair-db-service-spring-boot-starter</artifactId>
        <version>${geoair.version}</version>
      </dependency>

      <dependency>
        <groupId>cn.geoair.devkit</groupId>
        <artifactId>geoair-dynamic-ds</artifactId>
        <version>${geoair.version}</version>
      </dependency>

      <dependency>
        <groupId>cn.geoair.devkit</groupId>
        <artifactId>geoair-jts-all</artifactId>
        <version>${geoair.version}</version>
      </dependency>

      <dependency>
        <groupId>cn.geoair.devkit</groupId>
        <artifactId>geoair-real-mvt</artifactId>
        <version>${geoair.version}</version>
      </dependency>
      <dependency>
        <groupId>cn.geoair.devkit</groupId>
        <artifactId>geoair-geo-tools</artifactId>
        <version>${geoair.version}</version>
      </dependency>
      <dependency>
        <groupId>cn.geoair.devkit</groupId>
        <artifactId>geoair-mvt-tools</artifactId>
        <version>${geoair.version}</version>
      </dependency>
      <dependency>
        <groupId>cn.geoair.devkit</groupId>
        <artifactId>geoair-adv-query</artifactId>
        <version>${geoair.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <build>

  </build>

</project>
