# ????
spring.datasource.url=jdbc:postgresql://192.168.0.110:5432/test_dbName
spring.datasource.username=postgres
spring.datasource.password=XXXXX
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=50
spring.datasource.hikari.minimum-idle=5

# GeoAir ??????
spring.datasource.geoair.group-name=orderRdGroup
spring.datasource.geoair.master-data-source-id=master_db_01
spring.datasource.geoair.readwrite.enabled=true
spring.datasource.geoair.readwrite.read-strategy=WEIGHT

# ??????????????
spring.datasource.geoair.readwrite.read-data-sources[0].id=beijing_slave
spring.datasource.geoair.readwrite.read-data-sources[0].url=jdbc:postgresql://192.168.0.104:5432/test_dbName
spring.datasource.geoair.readwrite.read-data-sources[0].weight=50
spring.datasource.geoair.readwrite.read-data-sources[0].enabled=true

spring.datasource.geoair.readwrite.read-data-sources[1].id=shanghai_slave
spring.datasource.geoair.readwrite.read-data-sources[1].url=jdbc:postgresql://192.168.0.105:5432/test_dbName
spring.datasource.geoair.readwrite.read-data-sources[1].weight=30
spring.datasource.geoair.readwrite.read-data-sources[1].enabled=true

spring.datasource.geoair.readwrite.read-data-sources[2].id=guangzhou_slave
spring.datasource.geoair.readwrite.read-data-sources[2].url=jdbc:postgresql://192.168.0.106:5432/test_dbName
spring.datasource.geoair.readwrite.read-data-sources[2].weight=20
spring.datasource.geoair.readwrite.read-data-sources[2].enabled=true

spring.datasource.geoair.readwrite.read-data-sources[3].id=backup_slave
spring.datasource.geoair.readwrite.read-data-sources[3].url=jdbc:postgresql://192.168.0.107:5432/test_dbName
spring.datasource.geoair.readwrite.read-data-sources[3].weight=0
spring.datasource.geoair.readwrite.read-data-sources[3].enabled=false
