<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>cn.geoair.geo.dynamic</groupId>
        <artifactId>geoair-dynamic</artifactId>
        <version>23.1.2-M2</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <groupId>cn.geoair.geo.dynamic</groupId>
    <version>23.1.2-M2</version>
    <artifactId>geo-dynamic-mvt</artifactId>
    <name>geo-dynamic-mvt</name>

    <properties>
        <java.version>8</java.version>
        <geoair.version>23.1.2-M2</geoair.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    </properties>
    <description>mvt相关模块的功能组合</description>
    <packaging>pom</packaging>
    <url>https://gitee.com/geoair/geo-dynamic</url>

    <licenses>
        <license>
            <name>The Apache Software License, cn.geoair.map.dynamic.tools.Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
        </license>
    </licenses>

    <developers>
        <developer>
            <name>zhangfengji</name>
            <email>1159856928@qq.com</email>
            <organization>geoair</organization>
            <organizationUrl>https://xmt.geoair.cn/</organizationUrl>
        </developer>
    </developers>

    <scm>
        <connection>https://gitee.com/geoair/geo-dynamic.git</connection>
        <developerConnection>scm:git:ssh://git@gitee.com:geoair/geo-dynamic.git</developerConnection>
        <url>https://gitee.com/geoair/geo-dynamic</url>
    </scm>


    <modules>
        <module>geo-dynamic-real-mvt</module>
        <module>geo-dynamic-static-mvt-spark</module>
        <module>geo-dynamic-mvt-tools</module>
    </modules>


    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>cn.geoair.geo.dynamic</groupId>
                <artifactId>geo-dynamic-mvt-tools</artifactId>
                <version>${geoair.version}</version>
            </dependency>
            <dependency>
                <groupId>cn.geoair.geo.dynamic</groupId>
                <artifactId>geo-dynamic-real-mvt</artifactId>
                <version>${geoair.version}</version>
            </dependency>
            <dependency>
                <groupId>cn.geoair.geo.dynamic</groupId>
                <artifactId>geo-dynamic-static-mvt-spark</artifactId>
                <version>${geoair.version}</version>
            </dependency>

        </dependencies>


    </dependencyManagement>


</project>
