<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>cn.geoair.devkit</groupId>
        <artifactId>geoair-framework</artifactId>
        <version>J17-dev-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <groupId>cn.geoair.devkit</groupId>
    <artifactId>geoair-dependencies-bom</artifactId>
    <version>J17-dev-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>geoair-dependencies-bom</name>
    <description>GeoAir 第三方依赖版本管理 BOM</description>
    <url>https://github.com/geoair-cn/geoair</url>

    <licenses>
        <license>
            <name>The Apache Software License, Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
        </license>
    </licenses>

  <developers>
    <developer>
      <name>张逢吉</name>
      <email>zfj20250104@qq.com</email>
      <organization>geoair</organization>
      <organizationUrl>https://xmt.geoair.cn/</organizationUrl>
    </developer>
  </developers>

    <modules>
        <module>geoair-geotools-dependencies</module>
        <module>geoair-openapi-dependencies</module>
        <module>geoair-spring-dependencies</module>
        <module>geoair-common-dependencies</module>
    </modules>

    <scm>
        <connection>scm:git://github.com/geoair-cn/geoair.git</connection>
        <developerConnection>scm:git:https://github.com:geoair-cn/geoair.git</developerConnection>
        <tag>HEAD</tag>
        <url>https://github.com/geoair-cn/geoair</url>
    </scm>

    <dependencyManagement>
        <dependencies>

            <dependency>
                <groupId>cn.geoair.devkit</groupId>
                <artifactId>geoair-geotools-dependencies</artifactId>
                <version>${geoair.version}</version>

            </dependency>
            <dependency>
                <groupId>cn.geoair.devkit</groupId>
                <artifactId>geoair-openapi-dependencies</artifactId>
                <version>${geoair.version}</version>

            </dependency>
            <dependency>
                <groupId>cn.geoair.devkit</groupId>
                <artifactId>geoair-spring-dependencies</artifactId>
                <version>${geoair.version}</version>

            </dependency>
            <dependency>
                <groupId>cn.geoair.devkit</groupId>
                <artifactId>geoair-common-dependencies</artifactId>
                <version>${geoair.version}</version>

            </dependency>

        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-source-plugin</artifactId>
                    <version>${maven-source-plugin.version}</version>
                    <executions>
                        <execution>
                            <phase>compile</phase>
                            <goals>
                                <goal>jar-no-fork</goal>
                            </goals>
                            <configuration>
                                <attach>true</attach>
                                <classifier>sources</classifier>  <!-- 相同的 classifier！ -->
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${maven-compiler-plugin.version}</version>
                    <configuration>
                        <parameters>true</parameters>
                        <!-- 源码版本 -->
                        <source>17</source>
                        <!-- 目标字节码版本 -->
                        <target>17</target>
                        <!-- 编码（可选，避免中文乱码） -->
                        <encoding>UTF-8</encoding>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-javadoc-plugin</artifactId>
                    <version>${maven-javadoc-plugin.version}</version>
                    <executions>
                        <execution>
                            <id>attach-javadocs</id>
                            <goals>
                                <!-- 打包 javadoc.jar -->
                                <goal>jar</goal>
                                <!-- 编译时自动修复注释 -->
                                <goal>fix</goal>
                            </goals>
                        </execution>
                    </executions>
                    <configuration>
                        <!-- 自动修复类注释 -->
                        <fixClassComment>true</fixClassComment>
                        <!-- 自动修复方法注释 -->
                        <fixMethodComment>true</fixMethodComment>
                        <!-- 自动修复字段注释 -->
                        <fixFieldComment>true</fixFieldComment>
                        <version>false</version>
                        <author>false</author>
                        <!-- 开启严格模式，注释不规范直接报错 -->
                        <failOnError>false</failOnError>
                        <!-- 文档编码 UTF-8 -->
                        <encoding>UTF-8</encoding>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-gpg-plugin</artifactId>
                    <version>1.5</version>
                    <executions>
                        <execution>
                            <id>sign-artifacts</id>
                            <phase>verify</phase>
                            <goals>
                                <goal>sign</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.sonatype.central</groupId>
                    <artifactId>central-publishing-maven-plugin</artifactId>
                    <version>0.9.0</version>
                    <extensions>true</extensions>
                    <configuration>
                        <publishingServerId>central</publishingServerId>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>

        <plugins>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>${maven-jar-plugin.version}</version>
                <configuration>
                    <!--					<classifier>bak</classifier>-->
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven-compiler-plugin.version}</version>
                <configuration>
                    <parameters>true</parameters>
                    <!-- 源码版本 -->
                    <source>17</source>
                    <!-- 目标字节码版本 -->
                    <target>17</target>
                    <!-- 编码（可选，避免中文乱码） -->
                    <encoding>UTF-8</encoding>
                </configuration>
            </plugin>

            <!--生成源码插件-->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
            </plugin>

            <!--生成API文档插件-->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <executions>
                    <execution>
                        <id>attach-javadocs</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <encoding>UTF-8</encoding>
                    <failOnError>false</failOnError>
                    <!-- 忽略错误，继续执行 -->
                </configuration>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>central</id>
            <build>
                <!--发布到中央SNAPSHOT仓库插件-->
                <plugins>
                    <!--gpg插件-->
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-gpg-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>sign-artifacts</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>sign</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.sonatype.central</groupId>
                        <artifactId>central-publishing-maven-plugin</artifactId>
                        <version>0.9.0</version>
                        <extensions>true</extensions>
                        <configuration>
                            <publishingServerId>central</publishingServerId>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
            <distributionManagement>
                <repository>
                    <id>ossrh</id>
                    <url>https://central.sonatype.com/repository/maven-snapshots/</url>
                </repository>
                <snapshotRepository>
                    <id>ossrh</id>
                    <url>https://central.sonatype.com/repository/maven-snapshots/</url>
                </snapshotRepository>
            </distributionManagement>
        </profile>
        <profile>
            <id>code-style</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>com.spotify.fmt</groupId>
                        <artifactId>fmt-maven-plugin</artifactId>
                       <version>${fmt-maven-plugin.version}</version>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>format</goal>
                                </goals>
                            </execution>
                        </executions>
                        <configuration>
                            <verbose>false</verbose>
                            <filesNamePattern>.*\.java</filesNamePattern>
                            <skip>false</skip>
                            <style>aosp</style>
                        </configuration>
                    </plugin>
                    <!--          <plugin>-->
                    <!--            <groupId>net.revelc.code</groupId>-->
                    <!--            <artifactId>impsort-maven-plugin</artifactId>-->
                    <!--            <version>1.6.0</version>-->
                    <!--            <executions>-->
                    <!--              <execution>-->
                    <!--                <id>sort-imports</id>-->
                    <!--                <goals>-->
                    <!--                  <goal>sort</goal>-->
                    <!--                  &lt;!&ndash; runs at process-sources phase by default &ndash;&gt;-->
                    <!--                </goals>-->
                    <!--              </execution>-->
                    <!--            </executions>-->
                    <!--            <configuration>-->
                    <!--              <groups>*</groups>-->
                    <!--              &lt;!&ndash; 静态导入也统一规则 &ndash;&gt;-->
                    <!--              <staticGroups>*</staticGroups>-->
                    <!--              &lt;!&ndash; 保留：自动删除没用的 import &ndash;&gt;-->
                    <!--              <removeUnused>true</removeUnused>-->

                    <!--            </configuration>-->
                    <!--          </plugin>-->
                    <plugin>
                        <groupId>com.github.ekryd.sortpom</groupId>
                        <artifactId>sortpom-maven-plugin</artifactId>
                        <version>4.0.0</version>
                        <executions>
                            <execution>
                                <phase>verify</phase>
                                <goals>
                                    <goal>sort</goal>
                                </goals>
                            </execution>
                        </executions>
                        <configuration>
                            <skip>false</skip>
                            <keepBlankLines>true</keepBlankLines>
                            <sortDependencies>''</sortDependencies>
                            <spaceBeforeCloseEmptyElement>false</spaceBeforeCloseEmptyElement>
                            <createBackupFile>false</createBackupFile>
                            <verifyFail>stop</verifyFail>
                            <verifyFailOn>strict</verifyFailOn>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>code-check</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>com.github.spotbugs</groupId>
                        <artifactId>spotbugs-maven-plugin</artifactId>
                        <version>4.9.8.2</version>
                        <!-- Java8 最后稳定版 -->
                        <executions>
                            <execution>
                                <goals>
                                    <goal>check</goal>
                                    <!-- 构建时自动检查 -->
                                </goals>
                            </execution>
                        </executions>
                        <configuration>
                            <encoding>UTF-8</encoding>
                            <failOnError>false</failOnError>
                            <!-- 发现bug是否让构建失败 -->
                            <includeTests>false</includeTests>
                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>org.gaul</groupId>
                        <artifactId>modernizer-maven-plugin</artifactId>
                        <version>3.3.0</version>
                        <!-- Java8 稳定版 -->
                        <executions>
                            <execution>
                                <goals>
                                    <goal>modernizer</goal>
                                    <!-- 构建时自动检查 -->
                                </goals>
                            </execution>
                        </executions>
                        <configuration>
                            <javaVersion>17</javaVersion>
                            <!-- 发现问题是否让构建失败（企业一般设为false，只提醒） -->
                            <failOnViolations>false</failOnViolations>
                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-dependency-plugin</artifactId>
                        <version>${maven-dependency-plugin.version}</version>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>geoair-group-repo</id>
            <distributionManagement>
                <repository>
                    <id>gir-release</id>
                    <url>http://xmt.geoair.cn:32000/repository/109-release/</url>
                </repository>
                <snapshotRepository>
                    <id>gir-snapshot</id>
                    <url>http://xmt.geoair.cn:32000/repository/109-snapshot/</url>
                </snapshotRepository>
            </distributionManagement>
        </profile>
        <profile>
            <id>git-commit-id-gen</id>
            <build>
                <plugins>

                    <plugin>
                        <groupId>pl.project13.maven</groupId>
                        <artifactId>git-commit-id-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>get-the-git-infos</id>
                                <phase>initialize</phase>
                                <goals>
                                    <goal>revision</goal>
                                </goals>
                            </execution>
                        </executions>
                        <configuration>
                            <generateGitPropertiesFile>true</generateGitPropertiesFile>
                            <generateGitPropertiesFilename>${project.build.outputDirectory}/git.properties
                            </generateGitPropertiesFilename>

                            <!-- 包含提交信息相关属性（关键） -->
                            <includeOnlyProperties>
                                <includeOnlyProperty>^git.commit.id$</includeOnlyProperty>
                                <!-- 完整提交哈希 -->
                                <includeOnlyProperty>^git.commit.time$</includeOnlyProperty>
                                <!-- 提交时间 -->
                                <includeOnlyProperty>^git.commit.message.full$</includeOnlyProperty>
                                <!-- 完整提交信息 -->
                                <includeOnlyProperty>^git.commit.message.short$</includeOnlyProperty>
                                <!-- 提交标题（第一行） -->
                                <includeOnlyProperty>^git.branch$</includeOnlyProperty>
                                <!-- 提交标题（第一行） -->
                            </includeOnlyProperties>

                            <dateFormat>yyyy-MM-dd HH:mm:ss</dateFormat>
                            <dateFormatTimeZone>Asia/Shanghai</dateFormatTimeZone>
                            <verbose>false</verbose>
                            <skipPoms>true</skipPoms>
                        </configuration>
                    </plugin>

                </plugins>
            </build>
        </profile>
    </profiles>

</project>
