<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>cn.geoair.dependencies</groupId>
		<artifactId>geoair-module-pom</artifactId>
		<version>23.0.2</version>
		<relativePath>../pom.xml</relativePath>
	</parent>

	<artifactId>geoair-spring-module</artifactId>
	<name>geoair-spring-module</name>
	<packaging>pom</packaging>
	<description>geoair spring module</description>

	<url>https://gitee.com/geoair/geoair-dependencies</url>

	<licenses>
		<license>
			<name>The Apache Software License, Version 2.0</name>
			<url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
		</license>
	</licenses>

	<developers>
		<developer>
			<name>zhangfengji</name>
			<email>1159856928@qq.com</email>
			<organization>geoair</organization>
			<organizationUrl>https://xmt.geoair.cn/</organizationUrl>
		</developer>
	</developers>

	<scm>
		<connection>https://gitee.com/geoair/geoair-dependencies.git</connection>
		<developerConnection>scm:git:ssh://git@gitee.com:geoair/geoair-dependencies.git</developerConnection>
		<url>https://gitee.com/geoair/geoair-dependencies</url>
	</scm>



	<dependencyManagement>
	 <dependencies>
		 <dependency>
			 <groupId>org.springframework.boot</groupId>
			 <artifactId>spring-boot-dependencies</artifactId>
			 <version>${spring-boot.version}</version>
			 <type>pom</type>
			 <scope>import</scope>
		 </dependency>

		 <dependency>
			 <groupId>org.springframework.cloud</groupId>
			 <artifactId>spring-cloud-dependencies</artifactId>
			 <version>2021.0.4</version>
			 <type>pom</type>
			 <scope>import</scope>
		 </dependency>

		 <dependency>
			 <groupId>com.alibaba.spring</groupId>
			 <artifactId>spring-context-support</artifactId>
			 <version>1.0.11</version>
		 </dependency>

		 <dependency>
			 <groupId>com.alibaba.cloud</groupId>
			 <artifactId>spring-cloud-alibaba-dependencies</artifactId>
			 <version>2021.0.4.0</version>
			 <type>pom</type>
			 <scope>import</scope>
		 </dependency>
		 <dependency>
			 <groupId>org.redisson</groupId>
			 <artifactId>redisson-spring-boot-starter</artifactId>
			 <version>${redisson.version}</version>
		 </dependency>

	 </dependencies>
	</dependencyManagement>

	<dependencies></dependencies>

	<build>
		<pluginManagement>
			<plugins></plugins>
		</pluginManagement>

		<plugins></plugins>


	</build>

</project>
