<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>cn.geoair.orm</groupId>
        <artifactId>geoair-orm</artifactId>
        <!--		<version>23.0.3-SNAPSHOT&lt;!&ndash;gtcversion&ndash;&gt;</version>-->
        <version>23.0.3-SNAPSHOT<!--gtcversion--></version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>geoair-mybatis</artifactId>

    <packaging>jar</packaging>
    <name>geoair-mybatis</name>

    <url>https://gitee.com/geoair/geoair</url>

    <licenses>
        <license>
            <name>The Apache Software License, Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
        </license>
    </licenses>

    <developers>
        <developer>
            <name>zhangfengji</name>
            <email>1159856928@qq.com</email>
            <organization>geoair</organization>
            <organizationUrl>https://xmt.geoair.cn/</organizationUrl>
        </developer>
    </developers>

    <scm>
        <connection>https://gitee.com/geoair/geoair-dependencies.git</connection>
        <developerConnection>scm:git:ssh://git@gitee.com:geoair/geoair-dependencies.git</developerConnection>
        <url>https://gitee.com/geoair/geoair</url>
    </scm>

    <dependencies>

        <dependency>
            <groupId>cn.geoair</groupId>
            <artifactId>geoair-core</artifactId>
        </dependency>

        <dependency>
            <groupId>cn.geoair.orm</groupId>
            <artifactId>geoair-orm-base</artifactId>
        </dependency>

        <dependency>
            <groupId>org.mybatis</groupId>
            <artifactId>mybatis</artifactId>
        </dependency>

        <dependency>
            <groupId>org.mybatis</groupId>
            <artifactId>mybatis-spring</artifactId>
        </dependency>

        <dependency>
            <groupId>com.github.pagehelper</groupId>
            <artifactId>pagehelper</artifactId>
        </dependency>
    </dependencies>

</project>
