<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>
    <parent>
       <groupId>cn.geoair.devkit</groupId>
        <artifactId>geoair-standard</artifactId>
        <version>J8.1.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
   <groupId>cn.geoair.devkit</groupId>
    <artifactId>geoair-core</artifactId>
    <version>J8.1.0-SNAPSHOT</version>
    <name>geoair-core</name>
    <packaging>jar</packaging>
    <description>核心工具包</description>
    <properties>
    </properties>
    <url>https://github.com/geoair-cn/geoair</url>

    <licenses>
        <license>
            <name>The Apache Software License, Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
        </license>
    </licenses>

    <developers>
        <developer>
            <name>zhangfengji</name>
            <email>1159856928@qq.com</email>
            <organization>geoair</organization>
            <organizationUrl>https://xmt.geoair.cn/</organizationUrl>
        </developer>
    </developers>

    <scm>
        <connection>scm:git://github.com/geoair-cn/geoair.git</connection>
        <developerConnection>scm:git:https://github.com:geoair-cn/geoair.git</developerConnection>
        <url>https://github.com/geoair-cn/geoair</url>
        <tag>HEAD</tag>
    </scm>
    <dependencies>

        <dependency>
           <groupId>cn.geoair.devkit</groupId>
            <artifactId>geoair-base</artifactId>
            <version>${geoair.version}</version>
        </dependency>

        <dependency>
           <groupId>cn.geoair.devkit</groupId>
            <artifactId>geoair-web</artifactId>
            <version>${geoair.version}</version>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
            <version>${spring.version}</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-web</artifactId>
            <version>${spring.version}</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>redis.clients</groupId>
            <artifactId>jedis</artifactId>
            <version>${jedis.version}</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-all</artifactId>
            <version>${hutool.version}</version>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>javax.servlet-api</artifactId>
            <version>${servlet-api.version}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>com.alibaba.fastjson2</groupId>
            <artifactId>fastjson2</artifactId>
            <version>${fastjson.version}</version>
        </dependency>

        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>fastjson</artifactId>
            <version>${fastjson1x.version}</version>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>${gson.version}</version>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>${jackson.version.databind}</version>
            <optional>true</optional>
        </dependency>

        <!--
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-cache</artifactId>
        </dependency>
        -->
        <dependency>
            <groupId>javax.cache</groupId>
            <artifactId>cache-api</artifactId>
            <version>${javax-cache.version}</version>
            <optional>true</optional>
        </dependency>

    </dependencies>


</project>
