<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
       <groupId>cn.geoair</groupId>
        <artifactId>geoair-geo</artifactId>
        <version>J8.1.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
   <groupId>cn.geoair</groupId>
    <version>J8.1.0-SNAPSHOT</version>
    <artifactId>geoair-file-tran</artifactId>
    <name>geoair-file-tran</name>
    <properties>
        <java.version>8</java.version>
        <geoair.version>J8.1.0-SNAPSHOT</geoair.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    </properties>

    <packaging>pom</packaging>
    <description>
        geoair-file-tran
        文件与数据库的转换支持包,基于geotools实现
    </description>

    <url>https://gitee.com/geoair/geoair</url>

    <licenses>
        <license>
            <name>The Apache Software License, cn.geoair.map.dynamic.tools.Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
        </license>
    </licenses>

    <developers>
        <developer>
            <name>zhangfengji</name>
            <email>1159856928@qq.com</email>
            <organization>geoair</organization>
            <organizationUrl>https://xmt.geoair.cn/</organizationUrl>
        </developer>
    </developers>

    <scm>
        <connection>https://gitee.com/geoair/geoair.git</connection>
        <developerConnection>scm:git:ssh://git@gitee.com:geoair/geoair.git</developerConnection>
        <url>https://gitee.com/geoair/geoair</url>
    </scm>

    <modules>
        <module>geoair-file-core</module>
        <module>geoair-file-geojson</module>
        <module>geoair-file-postgis</module>
        <module>geoair-file-test</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
               <groupId>cn.geoair</groupId>
                <artifactId>geoair-file-core</artifactId>
                <version>${geoair.version}</version>
            </dependency>
            <dependency>
               <groupId>cn.geoair</groupId>
                <artifactId>geoair-file-geojson</artifactId>
                <version>${geoair.version}</version>
            </dependency>
            <dependency>
               <groupId>cn.geoair</groupId>
                <artifactId>geoair-file-postgis</artifactId>
                <version>${geoair.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>8</source>
                    <target>8</target>
                    <encoding>UTF-8</encoding>
                </configuration>
            </plugin>

        </plugins>
    </build>

</project>
