<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>cn.geoair.devkit</groupId>
    <artifactId>geoair-geo</artifactId>
    <version>J8.1.2-SNAPSHOT</version>
    <relativePath>../pom.xml</relativePath>
  </parent>
  <groupId>cn.geoair.devkit</groupId>
  <artifactId>geoair-file-tran</artifactId>
  <version>J8.1.2-SNAPSHOT</version>

  <packaging>pom</packaging>
  <name>geoair-file-tran</name>
  <description>geoair-file-tran
        文件与数据库的转换支持包,基于geotools实现</description>

  <url>https://github.com/geoair-cn/geoair</url>

  <licenses>
    <license>
      <name>The Apache Software License, cn.geoair.map.dynamic.tools.Version 2.0</name>
      <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
    </license>
  </licenses>

  <developers>
    <developer>
      <name>zhangfengji</name>
      <email>1159856928@qq.com</email>
      <organization>geoair</organization>
      <organizationUrl>https://xmt.geoair.cn/</organizationUrl>
    </developer>
  </developers>

  <modules>
    <module>geoair-file-core</module>
    <module>geoair-file-geojson</module>
    <module>geoair-file-postgis</module>
    <module>geoair-file-shp</module>
    <module>geoair-file-test</module>
  </modules>

  <scm>
    <connection>https://github.com/geoair-cn/geoair.git</connection>
    <developerConnection>scm:git:https://github.com:geoair-cn/geoair.git</developerConnection>
    <url>https://github.com/geoair-cn/geoair</url>
  </scm>
  <properties>
    <java.version>8</java.version>
    <geoair.version>J8.1.2-SNAPSHOT</geoair.version>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>cn.geoair.devkit</groupId>
        <artifactId>geoair-file-core</artifactId>
        <version>${geoair.version}</version>
      </dependency>
      <dependency>
        <groupId>cn.geoair.devkit</groupId>
        <artifactId>geoair-file-geojson</artifactId>
        <version>${geoair.version}</version>
      </dependency>
      <dependency>
        <groupId>cn.geoair.devkit</groupId>
        <artifactId>geoair-file-postgis</artifactId>
        <version>${geoair.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>${maven-compiler-plugin.version}</version>
        <configuration>
          <parameters>true</parameters>
          <!-- 源码版本 -->
          <source>8</source>
          <!-- 目标字节码版本 -->
          <target>8</target>
          <!-- 编码（可选，避免中文乱码） -->
          <encoding>UTF-8</encoding>
        </configuration>
      </plugin>

    </plugins>
  </build>

</project>
