package cn.geoair.comp.dynamic.ds.readwrite.proxy;

import cn.geoair.comp.dynamic.ds.readwrite.GirGroupByIdDataSource;
import cn.geoair.comp.dynamic.ds.readwrite.GirReadWriteDataSource;
import cn.geoair.comp.dynamic.ds.readwrite.log.RdLog;
import cn.geoair.comp.dynamic.ds.readwrite.proxy.druid.*;
import java.io.InputStream;
import java.io.Reader;
import java.math.BigDecimal;
import java.net.URL;
import java.sql.*;
import java.util.Arrays;
import java.util.Calendar;
import java.util.HashMap;
import java.util.Map;

/**
 * 读写分离 PreparedStatement 代理（参考 Druid 完整实现）
 *
 * @author 张俊
 * @date Created in 2026/5/28
 */
public class ReadWriteSplitPreparedStatement extends ReadWriteSplitStatement
        implements PreparedStatement {

    private final String sql;
    private JdbcParameter[] parameters;
    private int parametersSize;
    private Map<Integer, JdbcParameter> paramMap;

    // 真实的 PreparedStatement（延迟创建）
    private PreparedStatement realStatement;

    // 结果集参数
    private int resultSetType = ResultSet.TYPE_FORWARD_ONLY;
    private int resultSetConcurrency = ResultSet.CONCUR_READ_ONLY;
    private int resultSetHoldability = ResultSet.HOLD_CURSORS_OVER_COMMIT;

    // 自动生成键参数
    private int autoGeneratedKeys = -1;
    private int[] columnIndexes;
    private String[] columnNames;

    public ReadWriteSplitPreparedStatement(ReadWriteSplitConnection connection, String sql) {
        super(connection);
        this.sql = sql;

        // 解析 SQL 中的参数数量（跳过引号内的 ?）
        this.parameters = new JdbcParameter[getParamCount(sql)];
    }

    public ReadWriteSplitPreparedStatement(
            ReadWriteSplitConnection connection,
            String sql,
            int resultSetType,
            int resultSetConcurrency) {
        this(connection, sql);
        this.resultSetType = resultSetType;
        this.resultSetConcurrency = resultSetConcurrency;
    }

    public ReadWriteSplitPreparedStatement(
            ReadWriteSplitConnection connection,
            String sql,
            int resultSetType,
            int resultSetConcurrency,
            int resultSetHoldability) {
        this(connection, sql, resultSetType, resultSetConcurrency);
        this.resultSetHoldability = resultSetHoldability;
    }

    public ReadWriteSplitPreparedStatement(
            ReadWriteSplitConnection connection, String sql, int autoGeneratedKeys) {
        this(connection, sql);
        this.autoGeneratedKeys = autoGeneratedKeys;
    }

    public ReadWriteSplitPreparedStatement(
            ReadWriteSplitConnection connection, String sql, int[] columnIndexes) {
        this(connection, sql);
        this.columnIndexes = columnIndexes;
    }

    public ReadWriteSplitPreparedStatement(
            ReadWriteSplitConnection connection, String sql, String[] columnNames) {
        this(connection, sql);
        this.columnNames = columnNames;
    }

    /** 解析 SQL 中的参数数量（跳过引号内的 ?） */
    private int getParamCount(String sql) {
        char quote = 0;
        int paramCount = 0;
        for (int i = 0; i < sql.length(); ++i) {
            char ch = sql.charAt(i);

            if (ch == '\'') {
                if (quote == 0) {
                    quote = ch;
                } else if (quote == '\'') {
                    quote = 0;
                }
            } else if (ch == '"') {
                if (quote == 0) {
                    quote = ch;
                } else if (quote == '"') {
                    quote = 0;
                }
            }

            if (quote == 0 && ch == '?') {
                paramCount++;
            }
        }
        return paramCount;
    }

    /** 设置参数（JDBC 索引从 1 开始） */
    private void setParameter(int jdbcIndex, JdbcParameter parameter) {
        int index = jdbcIndex - 1;

        if (jdbcIndex > parametersSize) {
            parametersSize = jdbcIndex;
        }
        if (parametersSize >= parameters.length) {
            int oldCapacity = parameters.length;
            int newCapacity = oldCapacity + (oldCapacity >> 1);
            if (newCapacity <= 4) {
                newCapacity = 4;
            }
            parameters = Arrays.copyOf(parameters, newCapacity);
        }
        parameters[index] = parameter;

        // 清空懒加载的 Map
        if (paramMap != null) {
            paramMap = null;
        }
    }

    /** 获取所有参数 */
    public Map<Integer, JdbcParameter> getParameters() {
        if (paramMap == null) {
            paramMap = new HashMap<>(parametersSize);
            for (int i = 0; i < parametersSize; ++i) {
                if (parameters[i] != null) {
                    paramMap.put(i + 1, parameters[i]);
                }
            }
        }
        return paramMap;
    }

    /** 获取真实的 PreparedStatement */
    private PreparedStatement getRealPreparedStatement() throws SQLException {
        if (realStatement != null) {
            return realStatement;
        }

        // 根据 SQL 路由获取连接
        Connection conn = getConnectionBySQL();

        // 根据构造参数创建 PreparedStatement
        if (autoGeneratedKeys != -1) {
            realStatement = conn.prepareStatement(sql, autoGeneratedKeys);
        } else if (columnIndexes != null) {
            realStatement = conn.prepareStatement(sql, columnIndexes);
        } else if (columnNames != null) {
            realStatement = conn.prepareStatement(sql, columnNames);
        } else if (resultSetHoldability != ResultSet.HOLD_CURSORS_OVER_COMMIT) {
            realStatement =
                    conn.prepareStatement(
                            sql, resultSetType, resultSetConcurrency, resultSetHoldability);
        } else if (resultSetType != ResultSet.TYPE_FORWARD_ONLY
                || resultSetConcurrency != ResultSet.CONCUR_READ_ONLY) {
            realStatement = conn.prepareStatement(sql, resultSetType, resultSetConcurrency);
        } else {
            realStatement = conn.prepareStatement(sql);
        }

        // 应用已缓存的所有参数
        applyCachedParameters();

        RdLog.getInstance()
                .debug("创建真实的 PreparedStatement, sql: {}, 路由: {}", sql, getTargetDataSourceType());

        return realStatement;
    }

    /** 根据 SQL 路由获取连接 */
    private Connection getConnectionBySQL() throws SQLException {
        ReadWriteSplitConnection conn = (ReadWriteSplitConnection) getConnection();
        return conn.getConnection(sql);
    }

    /** 获取目标数据源类型 */
    private String getTargetDataSourceType() throws SQLException {
        ReadWriteSplitConnection conn = (ReadWriteSplitConnection) getConnection();
        GirReadWriteDataSource ds = conn.getDataSource();
        if (ds == null) {
            return "未知";
        }
        return ds.getDataSourceBySQL(sql) instanceof GirGroupByIdDataSource ? "从库" : "主库";
    }

    /** 应用缓存的所有参数到真实 Statement */
    private void applyCachedParameters() throws SQLException {
        if (realStatement == null) {
            return;
        }
        for (int i = 0; i < parametersSize; i++) {
            JdbcParameter param = parameters[i];
            if (param != null) {
                applyParameter(realStatement, i + 1, param);
            }
        }
    }

    /** 应用单个参数 */
    private void applyParameter(PreparedStatement stmt, int index, JdbcParameter param)
            throws SQLException {
        Object value = param.getValue();
        int sqlType = param.getSqlType();
        long length = param.getLength();
        Calendar calendar = param.getCalendar();

        if (value == null) {
            stmt.setNull(index, sqlType);
            return;
        }

        switch (sqlType) {
            case Types.BOOLEAN:
                stmt.setBoolean(index, (Boolean) value);
                break;
            case Types.INTEGER:
                stmt.setInt(index, (Integer) value);
                break;
            case Types.BIGINT:
                stmt.setLong(index, (Long) value);
                break;
            case Types.TINYINT:
                stmt.setByte(index, (Byte) value);
                break;
            case Types.SMALLINT:
                stmt.setShort(index, (Short) value);
                break;
            case Types.FLOAT:
                stmt.setFloat(index, (Float) value);
                break;
            case Types.DOUBLE:
                stmt.setDouble(index, (Double) value);
                break;
            case Types.VARCHAR:
            case Types.CHAR:
            case Types.NVARCHAR:
                stmt.setString(index, (String) value);
                break;
            case Types.DECIMAL:
                stmt.setBigDecimal(index, (BigDecimal) value);
                break;
            case Types.DATE:
                if (calendar != null) {
                    stmt.setDate(index, (java.sql.Date) value, calendar);
                } else {
                    stmt.setDate(index, (java.sql.Date) value);
                }
                break;
            case Types.TIME:
                if (calendar != null) {
                    stmt.setTime(index, (java.sql.Time) value, calendar);
                } else {
                    stmt.setTime(index, (java.sql.Time) value);
                }
                break;
            case Types.TIMESTAMP:
                if (calendar != null) {
                    stmt.setTimestamp(index, (java.sql.Timestamp) value, calendar);
                } else {
                    stmt.setTimestamp(index, (java.sql.Timestamp) value);
                }
                break;
            case Types.BLOB:
                if (value instanceof Blob) {
                    stmt.setBlob(index, (Blob) value);
                } else if (value instanceof InputStream) {
                    stmt.setBlob(index, (InputStream) value, length);
                }
                break;
            case Types.CLOB:
                if (value instanceof Clob) {
                    stmt.setClob(index, (Clob) value);
                } else if (value instanceof Reader) {
                    stmt.setClob(index, (Reader) value, length);
                }
                break;
            case Types.NCLOB:
                if (value instanceof NClob) {
                    stmt.setNClob(index, (NClob) value);
                } else if (value instanceof Reader) {
                    stmt.setNClob(index, (Reader) value, length);
                }
                break;
            default:
                stmt.setObject(index, value, sqlType);
        }
    }

    @Override
    public void setNull(int parameterIndex, int sqlType) throws SQLException {
        setParameter(parameterIndex, createParameterNull(sqlType));
    }

    @Override
    public void setBoolean(int parameterIndex, boolean x) throws SQLException {
        setParameter(parameterIndex, createParameter(Types.BOOLEAN, x));
    }

    @Override
    public void setByte(int parameterIndex, byte x) throws SQLException {
        setParameter(parameterIndex, createParameter(Types.TINYINT, x));
    }

    @Override
    public void setShort(int parameterIndex, short x) throws SQLException {
        setParameter(parameterIndex, createParameter(Types.SMALLINT, x));
    }

    @Override
    public void setInt(int parameterIndex, int x) throws SQLException {
        setParameter(parameterIndex, createParemeter(x));
    }

    @Override
    public void setLong(int parameterIndex, long x) throws SQLException {
        setParameter(parameterIndex, createParameter(x));
    }

    @Override
    public void setFloat(int parameterIndex, float x) throws SQLException {
        setParameter(parameterIndex, createParameter(Types.FLOAT, x));
    }

    @Override
    public void setDouble(int parameterIndex, double x) throws SQLException {
        setParameter(parameterIndex, createParameter(Types.DOUBLE, x));
    }

    @Override
    public void setBigDecimal(int parameterIndex, BigDecimal x) throws SQLException {
        setParameter(parameterIndex, createParameter(x));
    }

    @Override
    public void setString(int parameterIndex, String x) throws SQLException {
        setParameter(parameterIndex, createParameter(x));
    }

    @Override
    public void setBytes(int parameterIndex, byte[] x) throws SQLException {
        setParameter(parameterIndex, createParameter(JdbcParameter.TYPE.BYTES, x));
    }

    @Override
    public void setDate(int parameterIndex, java.sql.Date x) throws SQLException {
        setParameter(parameterIndex, createParameter(x));
    }

    @Override
    public void setTime(int parameterIndex, Time x) throws SQLException {
        setParameter(parameterIndex, createParameter(Types.TIME, x));
    }

    @Override
    public void setTimestamp(int parameterIndex, Timestamp x) throws SQLException {
        setParameter(parameterIndex, createParameter(Types.TIMESTAMP, x));
    }

    @Override
    public void setAsciiStream(int parameterIndex, InputStream x, int length) throws SQLException {
        setParameter(
                parameterIndex, createParameter(JdbcParameter.TYPE.AsciiInputStream, x, length));
    }

    @Override
    @Deprecated
    public void setUnicodeStream(int parameterIndex, InputStream x, int length)
            throws SQLException {
        setParameter(parameterIndex, createParameter(JdbcParameter.TYPE.UnicodeStream, x, length));
    }

    @Override
    public void setBinaryStream(int parameterIndex, InputStream x, int length) throws SQLException {
        setParameter(
                parameterIndex, createParameter(JdbcParameter.TYPE.BinaryInputStream, x, length));
    }

    @Override
    public void clearParameters() throws SQLException {
        if (parametersSize > 0) {
            for (int i = 0; i < parametersSize; i++) {
                parameters[i] = null;
            }
            parametersSize = 0;
            if (paramMap != null) {
                paramMap = null;
            }
        }
    }

    @Override
    public void setObject(int parameterIndex, Object x, int targetSqlType) throws SQLException {
        setParameter(parameterIndex, createParameter(targetSqlType, x));
    }

    @Override
    public void setObject(int parameterIndex, Object x) throws SQLException {
        setObjectParameter(parameterIndex, x);
    }

    @Override
    public void setCharacterStream(int parameterIndex, Reader reader, int length)
            throws SQLException {
        setParameter(
                parameterIndex,
                createParameter(JdbcParameter.TYPE.CharacterInputStream, reader, length));
    }

    @Override
    public void setRef(int parameterIndex, Ref x) throws SQLException {
        setParameter(parameterIndex, createParameter(Types.REF, x));
    }

    @Override
    public void setBlob(int parameterIndex, Blob x) throws SQLException {
        setParameter(parameterIndex, createParameter(Types.BLOB, x));
    }

    @Override
    public void setClob(int parameterIndex, Clob x) throws SQLException {
        setParameter(parameterIndex, createParameter(Types.CLOB, x));
    }

    @Override
    public void setArray(int parameterIndex, Array x) throws SQLException {
        setParameter(parameterIndex, createParameter(Types.ARRAY, x));
    }

    @Override
    public ResultSetMetaData getMetaData() throws SQLException {
        return getRealPreparedStatement().getMetaData();
    }

    @Override
    public void setDate(int parameterIndex, java.sql.Date x, Calendar cal) throws SQLException {
        setParameter(parameterIndex, createParameter(Types.DATE, x, cal));
    }

    @Override
    public void setTime(int parameterIndex, Time x, Calendar cal) throws SQLException {
        setParameter(parameterIndex, createParameter(Types.TIME, x, cal));
    }

    @Override
    public void setTimestamp(int parameterIndex, Timestamp x, Calendar cal) throws SQLException {
        setParameter(parameterIndex, createParameter(Types.TIMESTAMP, x, cal));
    }

    @Override
    public void setNull(int parameterIndex, int sqlType, String typeName) throws SQLException {
        setParameter(parameterIndex, JdbcParameterNull.valueOf(sqlType));
    }

    @Override
    public void setURL(int parameterIndex, URL x) throws SQLException {
        setParameter(parameterIndex, createParameter(JdbcParameter.TYPE.URL, x));
    }

    @Override
    public ParameterMetaData getParameterMetaData() throws SQLException {
        return getRealPreparedStatement().getParameterMetaData();
    }

    @Override
    public void setRowId(int parameterIndex, RowId x) throws SQLException {
        setParameter(parameterIndex, createParameter(Types.ROWID, x));
    }

    @Override
    public void setNString(int parameterIndex, String value) throws SQLException {
        setParameter(parameterIndex, createParameter(Types.NVARCHAR, value));
    }

    @Override
    public void setNCharacterStream(int parameterIndex, Reader value, long length)
            throws SQLException {
        setParameter(
                parameterIndex,
                createParameter(JdbcParameter.TYPE.NCharacterInputStream, value, length));
    }

    @Override
    public void setNClob(int parameterIndex, NClob value) throws SQLException {
        setParameter(parameterIndex, createParameter(Types.NCLOB, value));
    }

    @Override
    public void setClob(int parameterIndex, Reader reader, long length) throws SQLException {
        setParameter(parameterIndex, createParameter(Types.CLOB, reader, length));
    }

    @Override
    public void setBlob(int parameterIndex, InputStream inputStream, long length)
            throws SQLException {
        setParameter(parameterIndex, createParameter(Types.BLOB, inputStream, length));
    }

    @Override
    public void setNClob(int parameterIndex, Reader reader, long length) throws SQLException {
        setParameter(parameterIndex, createParameter(Types.NCLOB, reader, length));
    }

    @Override
    public void setSQLXML(int parameterIndex, SQLXML xmlObject) throws SQLException {
        setParameter(parameterIndex, createParameter(Types.SQLXML, xmlObject));
    }

    @Override
    public void setObject(int parameterIndex, Object x, int targetSqlType, int scaleOrLength)
            throws SQLException {
        setParameter(parameterIndex, createParameter(x, targetSqlType, scaleOrLength));
    }

    @Override
    public void setAsciiStream(int parameterIndex, InputStream x, long length) throws SQLException {
        setParameter(
                parameterIndex, createParameter(JdbcParameter.TYPE.AsciiInputStream, x, length));
    }

    @Override
    public void setBinaryStream(int parameterIndex, InputStream x, long length)
            throws SQLException {
        setParameter(
                parameterIndex, createParameter(JdbcParameter.TYPE.BinaryInputStream, x, length));
    }

    @Override
    public void setCharacterStream(int parameterIndex, Reader reader, long length)
            throws SQLException {
        setParameter(
                parameterIndex,
                createParameter(JdbcParameter.TYPE.CharacterInputStream, reader, length));
    }

    @Override
    public void setAsciiStream(int parameterIndex, InputStream x) throws SQLException {
        setParameter(parameterIndex, createParameter(JdbcParameter.TYPE.AsciiInputStream, x));
    }

    @Override
    public void setBinaryStream(int parameterIndex, InputStream x) throws SQLException {
        setParameter(parameterIndex, createParameter(JdbcParameter.TYPE.BinaryInputStream, x));
    }

    @Override
    public void setCharacterStream(int parameterIndex, Reader reader) throws SQLException {
        setParameter(
                parameterIndex, createParameter(JdbcParameter.TYPE.CharacterInputStream, reader));
    }

    @Override
    public void setNCharacterStream(int parameterIndex, Reader value) throws SQLException {
        setParameter(
                parameterIndex, createParameter(JdbcParameter.TYPE.NCharacterInputStream, value));
    }

    @Override
    public void setClob(int parameterIndex, Reader reader) throws SQLException {
        setParameter(parameterIndex, createParameter(Types.CLOB, reader));
    }

    @Override
    public void setBlob(int parameterIndex, InputStream inputStream) throws SQLException {
        setParameter(parameterIndex, createParameter(Types.BLOB, inputStream));
    }

    @Override
    public void setNClob(int parameterIndex, Reader reader) throws SQLException {
        setParameter(parameterIndex, createParameter(Types.NCLOB, reader));
    }

    // ==================== 执行方法 ====================

    @Override
    public ResultSet executeQuery() throws SQLException {
        PreparedStatement stmt = getRealPreparedStatement();
        return stmt.executeQuery();
    }

    @Override
    public int executeUpdate() throws SQLException {
        PreparedStatement stmt = getRealPreparedStatement();
        return stmt.executeUpdate();
    }

    @Override
    public boolean execute() throws SQLException {
        PreparedStatement stmt = getRealPreparedStatement();
        return stmt.execute();
    }

    @Override
    public void addBatch() throws SQLException {
        PreparedStatement stmt = getRealPreparedStatement();
        stmt.addBatch();
    }

    @Override
    public int[] executeBatch() throws SQLException {
        PreparedStatement stmt = getRealPreparedStatement();
        return stmt.executeBatch();
    }

    @Override
    public void clearBatch() throws SQLException {
        if (realStatement != null) {
            realStatement.clearBatch();
        }
    }

    @Override
    public ResultSet getGeneratedKeys() throws SQLException {
        PreparedStatement stmt = getRealPreparedStatement();
        return stmt.getGeneratedKeys();
    }

    // ==================== 关闭和资源释放 ====================

    @Override
    public void close() throws SQLException {
        if (realStatement != null && !realStatement.isClosed()) {
            realStatement.close();
        }
        realStatement = null;
        clearParameters();
    }

    @Override
    public boolean isClosed() throws SQLException {
        return realStatement == null || realStatement.isClosed();
    }

    @Override
    public Connection getConnection() throws SQLException {
        return super.getConnection();
    }

    // ==================== 其他 Statement 方法 ====================

    @Override
    public ResultSet getResultSet() throws SQLException {
        return realStatement != null ? realStatement.getResultSet() : null;
    }

    @Override
    public int getUpdateCount() throws SQLException {
        return realStatement != null ? realStatement.getUpdateCount() : -1;
    }

    @Override
    public boolean getMoreResults() throws SQLException {
        return realStatement != null && realStatement.getMoreResults();
    }

    @Override
    public void setFetchSize(int rows) throws SQLException {
        if (realStatement != null) {
            realStatement.setFetchSize(rows);
        }
    }

    @Override
    public int getFetchSize() throws SQLException {
        return realStatement != null ? realStatement.getFetchSize() : 0;
    }

    @Override
    public void setFetchDirection(int direction) throws SQLException {
        if (realStatement != null) {
            realStatement.setFetchDirection(direction);
        }
    }

    @Override
    public int getFetchDirection() throws SQLException {
        return realStatement != null ? realStatement.getFetchDirection() : ResultSet.FETCH_FORWARD;
    }

    @Override
    public void setMaxRows(int max) throws SQLException {
        if (realStatement != null) {
            realStatement.setMaxRows(max);
        }
    }

    @Override
    public int getMaxRows() throws SQLException {
        return realStatement != null ? realStatement.getMaxRows() : 0;
    }

    @Override
    public void setQueryTimeout(int seconds) throws SQLException {
        if (realStatement != null) {
            realStatement.setQueryTimeout(seconds);
        }
    }

    @Override
    public int getQueryTimeout() throws SQLException {
        return realStatement != null ? realStatement.getQueryTimeout() : 0;
    }

    @Override
    public void cancel() throws SQLException {
        if (realStatement != null) {
            realStatement.cancel();
        }
    }

    @Override
    public SQLWarning getWarnings() throws SQLException {
        return realStatement != null ? realStatement.getWarnings() : null;
    }

    @Override
    public void clearWarnings() throws SQLException {
        if (realStatement != null) {
            realStatement.clearWarnings();
        }
    }

    @Override
    public void setCursorName(String name) throws SQLException {
        if (realStatement != null) {
            realStatement.setCursorName(name);
        }
    }

    @Override
    public boolean getMoreResults(int current) throws SQLException {
        return realStatement != null && realStatement.getMoreResults(current);
    }

    @Override
    public int getResultSetConcurrency() throws SQLException {
        return resultSetConcurrency;
    }

    @Override
    public int getResultSetType() throws SQLException {
        return resultSetType;
    }

    @Override
    public int getResultSetHoldability() throws SQLException {
        return resultSetHoldability;
    }

    @Override
    public boolean isWrapperFor(Class<?> iface) throws SQLException {
        return iface.isInstance(this)
                || (realStatement != null && realStatement.isWrapperFor(iface));
    }

    @Override
    @SuppressWarnings("unchecked")
    public <T> T unwrap(Class<T> iface) throws SQLException {
        if (iface.isInstance(this)) {
            return iface.cast(this);
        }
        if (realStatement != null) {
            return realStatement.unwrap(iface);
        }
        throw new SQLException("No statement available");
    }

    private void setObjectParameter(int parameterIndex, Object x) {
        if (x == null) {
            setParameter(parameterIndex, createParameterNull(Types.OTHER));
            return;
        }

        Class<?> clazz = x.getClass();
        if (clazz == Byte.class) {
            setParameter(parameterIndex, createParameter(Types.TINYINT, x));
            return;
        }

        if (clazz == Short.class) {
            setParameter(parameterIndex, createParameter(Types.SMALLINT, x));
            return;
        }

        if (clazz == Integer.class) {
            setParameter(parameterIndex, createParemeter((Integer) x));
            return;
        }

        if (clazz == Long.class) {
            setParameter(parameterIndex, createParameter((Long) x));
            return;
        }

        if (clazz == String.class) {
            setParameter(parameterIndex, createParameter((String) x));
            return;
        }

        if (clazz == BigDecimal.class) {
            setParameter(parameterIndex, createParameter((BigDecimal) x));
            return;
        }

        if (clazz == Float.class) {
            setParameter(parameterIndex, new JdbcParameterImpl(Types.FLOAT, x));
            return;
        }

        if (clazz == Double.class) {
            setParameter(parameterIndex, new JdbcParameterImpl(Types.DOUBLE, x));
            return;
        }

        if (clazz == java.sql.Date.class || clazz == java.util.Date.class) {
            setParameter(parameterIndex, createParameter((java.util.Date) x));
            return;
        }

        if (clazz == java.sql.Timestamp.class) {
            setParameter(parameterIndex, createParameter((java.sql.Timestamp) x));
            return;
        }

        if (clazz == java.sql.Time.class) {
            setParameter(parameterIndex, new JdbcParameterImpl(Types.TIME, x));
            return;
        }

        if (clazz == Boolean.class) {
            setParameter(parameterIndex, new JdbcParameterImpl(Types.BOOLEAN, x));
            return;
        }

        if (clazz == byte[].class) {
            setParameter(parameterIndex, new JdbcParameterImpl(JdbcParameter.TYPE.BYTES, x));
            return;
        }

        if (x instanceof InputStream) {
            setParameter(
                    parameterIndex, new JdbcParameterImpl(JdbcParameter.TYPE.BinaryInputStream, x));
            return;
        }

        if (x instanceof Reader) {
            setParameter(
                    parameterIndex,
                    new JdbcParameterImpl(JdbcParameter.TYPE.CharacterInputStream, x));
            return;
        }

        if (x instanceof NClob) {
            setParameter(parameterIndex, new JdbcParameterImpl(Types.NCLOB, x));
            return;
        }

        if (x instanceof Clob) {
            setParameter(parameterIndex, new JdbcParameterImpl(Types.CLOB, x));
            return;
        }

        if (x instanceof Blob) {
            setParameter(parameterIndex, new JdbcParameterImpl(Types.BLOB, x));
            return;
        }

        String className = x.getClass().getName();

        if (className.equals("java.time.LocalTime")) {
            setParameter(parameterIndex, new JdbcParameterImpl(Types.TIME, x));
            return;
        }

        if (className.equals("java.time.LocalDate")) {
            setParameter(parameterIndex, new JdbcParameterImpl(Types.DATE, x));
            return;
        }

        if (className.equals("java.time.LocalDateTime")) {
            setParameter(parameterIndex, new JdbcParameterImpl(Types.TIMESTAMP, x));
            return;
        }

        if (className.equals("java.time.ZonedDateTime")) {
            setParameter(parameterIndex, new JdbcParameterImpl(Types.TIMESTAMP, x));
            return;
        }

        setParameter(parameterIndex, createParameter(Types.OTHER, null));
    }

    private JdbcParameter createParemeter(int x) {
        return JdbcParameterInt.valueOf(x);
    }

    private JdbcParameter createParameter(long x) {
        return JdbcParameterLong.valueOf(x);
    }

    private JdbcParameter createParameterNull(int sqlType) {
        return JdbcParameterNull.valueOf(sqlType);
    }

    private JdbcParameter createParameter(java.util.Date x) {
        if (x == null) {
            return JdbcParameterNull.DATE;
        }

        return new JdbcParameterDate(x);
    }

    private JdbcParameter createParameter(BigDecimal x) {
        if (x == null) {
            return JdbcParameterNull.DECIMAL;
        }

        return JdbcParameterDecimal.valueOf(x);
    }

    private JdbcParameter createParameter(String x) {
        if (x == null) {
            return JdbcParameterNull.VARCHAR;
        }

        if (x.isEmpty()) {
            return JdbcParameterString.empty;
        }

        return new JdbcParameterString(x);
    }

    private JdbcParameter createParameter(Timestamp x) {
        if (x == null) {
            return JdbcParameterNull.TIMESTAMP;
        }

        return new JdbcParameterTimestamp(x);
    }

    private JdbcParameter createParameter(Object x, int sqlType, int scaleOrLength) {
        if (x == null) {
            return JdbcParameterNull.valueOf(sqlType);
        }

        return new JdbcParameterImpl(sqlType, x, -1, null, scaleOrLength);
    }

    private JdbcParameter createParameter(int sqlType, Object value, long length) {
        if (value == null) {
            return JdbcParameterNull.valueOf(sqlType);
        }

        return new JdbcParameterImpl(sqlType, value, length);
    }

    private JdbcParameter createParameter(int sqlType, Object value) {
        if (value == null) {
            return JdbcParameterNull.valueOf(sqlType);
        }

        return new JdbcParameterImpl(sqlType, value);
    }

    public JdbcParameter createParameter(int sqlType, Object value, Calendar calendar) {
        if (value == null) {
            return JdbcParameterNull.valueOf(sqlType);
        }

        return new JdbcParameterImpl(sqlType, value, calendar);
    }
}
