spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    default: pro
geoair:
  apidoc:
    enable: true
    version: 6666
    auth:
      enable-auth: true
      username:
      password:

server:
  port: 8080
#server:
#  servlet:
#    context-path: /demo_context
#springdoc:
#  api-docs:
#    enabled: true
#  default-flat-param-object: true

