spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    default: pro
geoair:
  apidoc:
    enable: true
    version: 6666

server:
  port: 8080
#server:
#  servlet:
#    context-path: /demo_context

