<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>cn.geoair.devkit</groupId>
    <artifactId>geoair-base-parent</artifactId>
    <version>J17-dev-SNAPSHOT</version>
    <relativePath>../geoair-base-parent/pom.xml</relativePath>
  </parent>

  <groupId>cn.geoair.devkit</groupId>
  <artifactId>geoair-standard</artifactId>
  <version>J17-dev-SNAPSHOT</version>
  <packaging>pom</packaging>
  <name>geoair-standard</name>

  <description>基础标准库，设计初衷是通过spi实现相关常用的工具</description>

  <url>https://github.com/geoair-cn/geoair</url>

  <licenses>
    <license>
      <name>The Apache Software License, Version 2.0</name>
      <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
    </license>
  </licenses>

  <developers>
    <developer>
      <name>zhangfengji</name>
      <email>1159856928@qq.com</email>
      <organization>geoair</organization>
      <organizationUrl>https://xmt.geoair.cn/</organizationUrl>
    </developer>
  </developers>
  <modules>

    <module>geoair-tools</module>
    <module>geoair-base</module>
    <module>geoair-web</module>
    <module>geoair-core</module>
    <module>geoair-orm</module>
    <module>geoair-sdk</module>

  </modules>

  <scm>
    <connection>scm:git://github.com/geoair-cn/geoair.git</connection>
    <developerConnection>scm:git:https://github.com:geoair-cn/geoair.git</developerConnection>
    <tag>HEAD</tag>
    <url>https://github.com/geoair-cn/geoair</url>
  </scm>

  <properties>
    <geoair.version>J17-dev-SNAPSHOT</geoair.version>
    <skipTests>true</skipTests>
  </properties>

  <dependencyManagement>
    <dependencies>

      <!-- gir版本约束 -->
      <dependency>
        <groupId>cn.geoair.devkit</groupId>
        <artifactId>geoair-base</artifactId>
        <version>${geoair.version}</version>
      </dependency>

      <dependency>
        <groupId>cn.geoair.devkit</groupId>
        <artifactId>geoair-web</artifactId>
        <version>${geoair.version}</version>
      </dependency>

      <dependency>
        <groupId>cn.geoair.devkit</groupId>
        <artifactId>geoair-tools</artifactId>
        <version>${geoair.version}</version>
      </dependency>

      <dependency>
        <groupId>cn.geoair.devkit</groupId>
        <artifactId>geoair-core</artifactId>
        <version>${geoair.version}</version>
      </dependency>

      <dependency>
        <groupId>cn.geoair.devkit</groupId>
        <artifactId>geoair-sdk</artifactId>
        <version>${geoair.version}</version>
      </dependency>

      <dependency>
        <groupId>cn.geoair.devkit</groupId>
        <artifactId>geoair-orm-mybatis</artifactId>
        <version>${geoair.version}</version>
      </dependency>
      <dependency>
        <groupId>cn.geoair.devkit</groupId>
        <artifactId>geoair-orm-base</artifactId>
        <version>${geoair.version}</version>
      </dependency>
      <dependency>
        <groupId>cn.geoair.devkit</groupId>
        <artifactId>geoair-orm-mybatis-tk</artifactId>
        <version>${geoair.version}</version>
      </dependency>

      <dependency>
        <groupId>cn.geoair.devkit</groupId>
        <artifactId>geoair-orm-mybatis-plus</artifactId>
        <version>${geoair.version}</version>
      </dependency>

      <dependency>
        <groupId>cn.geoair.devkit</groupId>
        <artifactId>geoair-orm-springjpa</artifactId>
        <version>${geoair.version}</version>
      </dependency>

      <dependency>
        <groupId>cn.geoair.devkit</groupId>
        <artifactId>geoair-orm-spi</artifactId>
        <version>${geoair.version}</version>
      </dependency>
      <!-- soa -->

    </dependencies>
  </dependencyManagement>
  <dependencies></dependencies>
  <build>

  </build>

</project>
