package cn.geoair.comp.knife4j.ext.springfox.auto;

import cn.geoair.comp.knife4j.ext.config.GirSwaggerApiConfig;
import cn.geoair.comp.knife4j.ext.model.ApiModelInfo;
import cn.geoair.comp.knife4j.ext.model.DocketInfo;
import cn.geoair.comp.knife4j.ext.springfox.service.SpringAddtionalModelService;
import org.reflections.Reflections;
import org.springframework.beans.BeansException;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ApplicationContextAware;
import org.springframework.context.annotation.Bean;
import springfox.documentation.spring.web.plugins.Docket;
import springfox.documentation.swagger2.annotations.EnableSwagger2;

import java.util.*;

@EnableSwagger2
public class ApiRunner implements ApplicationContextAware {
    @Bean
    @ConditionalOnMissingBean(Reflections.class)
    Reflections reflections() {
        return new Reflections();
    }

    private GirSwaggerApiConfig apiConfig;

    private SpringAddtionalModelService springAddtionalModelService;

    /**
     * Spring自动注入ApplicationContext，并初始化配置属性
     */
    @Override
    public void setApplicationContext(ApplicationContext applicationContext) throws BeansException {
        // 初始化配置属性
        this.apiConfig = applicationContext.getBean(GirSwaggerApiConfig.class);
        this.springAddtionalModelService = applicationContext.getBean(SpringAddtionalModelService.class);
    }

    /**
     * 核心方法： 生成Docket
     */
    @Bean
    public Map<String, Docket> autoGenerateDockets() {
        List<DocketInfo> docketInfos = apiConfig.getDocketInfos();
        Map<String, Docket> docketMap = new LinkedHashMap<>();
        ApiModelInfo apiModelInfo1 = apiConfig.getApiModelInfo();
        for (DocketInfo docketInfo : docketInfos) {
            docketMap.put("docket-" + docketInfo.getGroupName().replaceAll("[^a-zA-Z0-9]", "-"), springAddtionalModelService.createApi(apiModelInfo1, docketInfo));
        }
        return docketMap;
    }


}
