package cn.geoair.comp.knife4j.ext.springfox.auto;

import cn.geoair.comp.knife4j.ext.config.GirSwaggerApiConfig;
import cn.geoair.comp.knife4j.ext.config.GirSwaggerProperties;
import cn.geoair.comp.knife4j.ext.model.ApiModelInfo;
import cn.geoair.comp.knife4j.ext.model.DocketInfo;
import cn.geoair.comp.knife4j.ext.springfox.service.SpringAddtionalModelService;

import org.reflections.Reflections;
import org.springframework.beans.BeansException;
import org.springframework.beans.factory.config.ConfigurableListableBeanFactory;
import org.springframework.beans.factory.support.BeanDefinitionRegistry;
import org.springframework.beans.factory.support.BeanDefinitionRegistryPostProcessor;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ApplicationContextAware;
import org.springframework.context.annotation.Bean;

import springfox.documentation.spring.web.plugins.Docket;
import springfox.documentation.swagger2.annotations.EnableSwagger2;

import java.util.ArrayList;
import java.util.List;

@EnableSwagger2
public class SpringFoxApiRunner
        implements ApplicationContextAware, BeanDefinitionRegistryPostProcessor {

    @Bean
    @ConditionalOnMissingBean(Reflections.class)
    Reflections reflections() {
        return new Reflections();
    }

    private ApplicationContext applicationContext;

    private GirSwaggerApiConfig apiConfig;

    private GirSwaggerProperties swaggerProperties;

    private SpringAddtionalModelService springAddtionalModelService;

    @Override
    public void setApplicationContext(ApplicationContext applicationContext) throws BeansException {
        this.applicationContext = applicationContext;
    }

    @Bean
    public List<Docket> autoGenerateDockets() {
        initDependencies();
        List<DocketInfo> docketInfos = apiConfig.getDocketInfos();
        List<Docket> dockets = new ArrayList<>();
        ApiModelInfo apiModelInfo1 = apiConfig.getApiModelInfo();

        for (DocketInfo docketInfo : docketInfos) {
            Docket docket =
                    springAddtionalModelService
                            .createApi(apiModelInfo1, docketInfo)
                            .groupName(docketInfo.getGroupName());
            docket.enable(swaggerProperties.isEnable());
            dockets.add(docket);
        }
        return dockets;
    }

    @Override
    public void postProcessBeanDefinitionRegistry(BeanDefinitionRegistry registry)
            throws BeansException {}

    @Override
    public void postProcessBeanFactory(ConfigurableListableBeanFactory beanFactory)
            throws BeansException {}

    private synchronized void initDependencies() {
        if (apiConfig == null) {
            this.apiConfig = applicationContext.getBean(GirSwaggerApiConfig.class);
            this.swaggerProperties = applicationContext.getBean(GirSwaggerProperties.class);
            this.springAddtionalModelService =
                    applicationContext.getBean(SpringAddtionalModelService.class);
        }
    }
}
