package cn.geoair.comp.knife4j.ext.springfox.auto;

import cn.geoair.comp.knife4j.ext.config.GirSwaggerApiConfig;
import cn.geoair.comp.knife4j.ext.model.ApiModelInfo;
import cn.geoair.comp.knife4j.ext.model.DocketInfo;
import cn.geoair.comp.knife4j.ext.springfox.service.SpringAddtionalModelService;

import org.reflections.Reflections;
import org.springframework.beans.BeansException;
import org.springframework.beans.factory.config.ConfigurableListableBeanFactory;
import org.springframework.beans.factory.support.BeanDefinitionRegistry;
import org.springframework.beans.factory.support.BeanDefinitionRegistryPostProcessor;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ApplicationContextAware;
import org.springframework.context.annotation.Bean;

import springfox.documentation.spring.web.plugins.Docket;
import springfox.documentation.swagger2.annotations.EnableSwagger2;

import java.util.ArrayList;
import java.util.List;

@EnableSwagger2
public class SpringFoxApiRunner
        implements ApplicationContextAware, BeanDefinitionRegistryPostProcessor {

    @Bean
    @ConditionalOnMissingBean(Reflections.class)
    Reflections reflections() {
        return new Reflections();
    }

    private ApplicationContext applicationContext; // 先保存ApplicationContext
    private GirSwaggerApiConfig apiConfig;
    private SpringAddtionalModelService springAddtionalModelService;

    /** Spring自动注入ApplicationContext */
    @Override
    public void setApplicationContext(ApplicationContext applicationContext) throws BeansException {
        this.applicationContext = applicationContext; // 仅保存上下文，不立即获取Bean
    }

    /** 核心方法：生成Docket Map（保留原方法，兼容原有引用） */
    @Bean
    public List<Docket> autoGenerateDockets() {
        // 延迟初始化依赖（确保此时ApplicationContext已完全就绪）
        initDependencies();

        List<DocketInfo> docketInfos = apiConfig.getDocketInfos();
        //        Map<String, Docket> docketMap = new LinkedHashMap<>();
        List<Docket> dockets = new ArrayList<>();
        ApiModelInfo apiModelInfo1 = apiConfig.getApiModelInfo();

        for (DocketInfo docketInfo : docketInfos) {
            Docket docket =
                    springAddtionalModelService
                            .createApi(apiModelInfo1, docketInfo)
                            .groupName(docketInfo.getGroupName()); // 确保分组名设置
            //            docketMap.put(docketInfo.getGroupName(), docket);
            dockets.add(docket);
        }
        return dockets;
    }

    /**
     * 关键修复：使用BeanDefinitionRegistryPostProcessor延迟注册Docket Bean
     * 执行时机：ApplicationContext刷新时，所有BeanDefinition加载完成后、Bean实例化前
     */
    @Override
    public void postProcessBeanDefinitionRegistry(BeanDefinitionRegistry registry)
            throws BeansException {
        //        // 延迟初始化依赖（此时ApplicationContext已就绪，可安全获取Bean）
        //        initDependencies();
        //
        //        List<DocketInfo> docketInfos = apiConfig.getDocketInfos();
        //        ApiModelInfo apiModelInfo1 = apiConfig.getApiModelInfo();
        //
        //        for (DocketInfo docketInfo : docketInfos) {
        //            String groupName = docketInfo.getGroupName();
        //            // 创建Docket实例并设置groupName（确保分组名称唯一）
        //            Docket docket =
        //                    springAddtionalModelService
        //                            .createApi(apiModelInfo1, docketInfo)
        //                            .groupName(groupName); // 显式指定分组名称
        //
        //            // 注册为独立的Bean，Bean名称使用分组名
        //            registry.registerBeanDefinition(
        //                    "docket-" + UUID.randomUUID().toString(),
        //                    BeanDefinitionBuilder.genericBeanDefinition(Docket.class, () ->
        // docket)
        //                            .getBeanDefinition());
        //        }
    }

    /** 空实现：BeanDefinitionRegistryPostProcessor的必填方法 */
    @Override
    public void postProcessBeanFactory(ConfigurableListableBeanFactory beanFactory)
            throws BeansException {
        // 无需处理
    }

    /** 延迟初始化依赖Bean（确保线程安全，只初始化一次） */
    private synchronized void initDependencies() {
        if (apiConfig == null) {
            this.apiConfig = applicationContext.getBean(GirSwaggerApiConfig.class);
            this.springAddtionalModelService =
                    applicationContext.getBean(SpringAddtionalModelService.class);
        }
    }

    // 移除原有的ImportBeanDefinitionRegistrar实现（已替换为BeanDefinitionRegistryPostProcessor）
}
