<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>cn.geoair.geo.dynamic</groupId>
        <artifactId>geo-dynamic-file-tran</artifactId>
        <version>23.1.1-M1</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <groupId>cn.geoair.geo.dynamic</groupId>
    <version>23.1.1-M1</version>
    <artifactId>geo-dynamic-file-geojson</artifactId>
    <name>geo-dynamic-file-geojson</name>


    <packaging>jar</packaging>
    <description>
        geo-dynamic-file-geojson
        geojson的实现类
    </description>

    <url>https://gitee.com/geoair/geo-dynamic</url>

    <licenses>
        <license>
            <name>The Apache Software License, cn.geoair.map.dynamic.tools.Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
        </license>
    </licenses>

    <developers>
        <developer>
            <name>zhangfengji</name>
            <email>1159856928@qq.com</email>
            <organization>geoair</organization>
            <organizationUrl>https://xmt.geoair.cn/</organizationUrl>
        </developer>
    </developers>

    <scm>
        <connection>https://gitee.com/geoair/geo-dynamic.git</connection>
        <developerConnection>scm:git:ssh://git@gitee.com:geoair/geo-dynamic.git</developerConnection>
        <url>https://gitee.com/geoair/geo-dynamic</url>
    </scm>

    <dependencies>
        <dependency>
            <groupId>cn.geoair.geo.dynamic</groupId>
            <artifactId>geo-dynamic-file-core</artifactId>
            <version>${geoair.version}</version>
        </dependency>

        <dependency>
            <groupId>org.geotools</groupId>
            <artifactId>gt-geojson</artifactId>
            <version>${geotools.version}</version>
        </dependency>
        <dependency>
            <groupId>org.geotools</groupId>
            <artifactId>gt-geojson-store</artifactId>
            <version>${geotools.version}</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
            <version>${lombok.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>8</source>
                    <target>8</target>
                    <encoding>UTF-8</encoding>
                </configuration>
            </plugin>

        </plugins>
    </build>

</project>
