<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>cn.geoair.geo.dynamic</groupId>
        <artifactId>geo-dynamic-mvt</artifactId>
        <version>23.1.1-beta4</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <artifactId>geo-dynamic-real-mvt</artifactId>
    <name>geo-dynamic-real-mvt</name>

    <packaging>jar</packaging>

    <description>实时矢量瓦片服务</description>

    <url>https://gitee.com/geoair/geo-dynamic</url>

    <licenses>
        <license>
            <name>The Apache Software License, cn.geoair.map.dynamic.tools.Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
        </license>
    </licenses>

    <developers>
        <developer>
            <name>zhangfengji</name>
            <email>1159856928@qq.com</email>
            <organization>geoair</organization>
            <organizationUrl>https://xmt.geoair.cn/</organizationUrl>
        </developer>
    </developers>

    <scm>
        <connection>https://gitee.com/geoair/geo-dynamic.git</connection>
        <developerConnection>scm:git:ssh://git@gitee.com:geoair/geo-dynamic.git</developerConnection>
        <url>https://gitee.com/geoair/geo-dynamic</url>
    </scm>

    <properties>
        <geotrellis.version>3.7.1</geotrellis.version>
    </properties>

    <dependencies>

        <dependency>
            <groupId>cn.geoair.geo.dynamic</groupId>
            <artifactId>geo-dynamic-mvt-tools</artifactId>
            <version>${geoair.version}</version>
        </dependency>

        <dependency>
            <groupId>cn.geoair.geo.dynamic</groupId>
            <artifactId>geo-dynamic-ds</artifactId>
            <version>${geoair.version}</version>
        </dependency>


        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-web</artifactId>
            <version>${spring.version}</version>
        </dependency>

        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-webmvc</artifactId>
            <version>${spring.version}</version>
        </dependency>


        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
            <optional>true</optional>
        </dependency>

        <!--        <dependency>-->
        <!--            <groupId>org.locationtech.geotrellis</groupId>-->
        <!--            <artifactId>geotrellis-vector_2.12</artifactId>-->
        <!--            <version>${geotrellis.version}</version>-->
        <!--        </dependency>-->
        <!--        <dependency>-->
        <!--            <groupId>org.locationtech.geotrellis</groupId>-->
        <!--            <artifactId>geotrellis-vectortile_2.12</artifactId>-->
        <!--            <version>${geotrellis.version}</version>-->
        <!--        </dependency>-->


    </dependencies>

</project>
