<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>cn.geoair.devkit</groupId>
    <artifactId>geoair-modules</artifactId>
    <version>J8.1.5</version>
    <relativePath>../pom.xml</relativePath>
  </parent>

  <groupId>cn.geoair.devkit</groupId>
  <artifactId>geoair-code-generator</artifactId>
  <version>J8.1.5</version>
  <packaging>pom</packaging>
  <name>geoair-code-generator</name>

  <description>代码生成器模块</description>

  <url>https://github.com/geoair-cn/geoair</url>

  <licenses>
    <license>
      <name>The Apache Software License, Version 2.0</name>
      <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
    </license>
  </licenses>

  <developers>
    <developer>
      <name>zhangfengji</name>
      <email>zhangjun7570@qq.com</email>
      <organization>geoair</organization>
      <organizationUrl>https://xmt.geoair.cn/</organizationUrl>
    </developer>
  </developers>

  <modules>
    <module>geoair-code-gen-module</module>
    <module>geoair-code-gen-demo</module>
  </modules>

  <scm>
    <connection>scm:git://github.com/geoair-cn/geoair.git</connection>
    <developerConnection>scm:git:https://github.com:geoair-cn/geoair.git</developerConnection>
    <tag>HEAD</tag>
    <url>https://github.com/geoair-cn/geoair</url>
  </scm>

  <properties>
    <skipTests>true</skipTests>
    <velocity.version>1.7</velocity.version>
    <commons.collections.version>3.2.2</commons.collections.version>
    <commons.io.version>2.11.0</commons.io.version>
    <commons.fileupload.version>1.4</commons.fileupload.version>
    <commons.collections.version>3.2.2</commons.collections.version>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.apache.velocity</groupId>
        <artifactId>velocity</artifactId>
        <version>${velocity.version}</version>
        <exclusions>
          <exclusion>
            <artifactId>commons-collections</artifactId>
            <groupId>commons-collections</groupId>
          </exclusion>
        </exclusions>
      </dependency>
      <dependency>
        <groupId>commons-collections</groupId>
        <artifactId>commons-collections</artifactId>
        <version>${commons.collections.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <build>
    <plugins></plugins>
  </build>
  <profiles>
    <profile>
      <!--      未开发完成，不发布到公网仓库-->
      <id>central</id>
      <build>
        <plugins>
          <plugin>
            <groupId>org.sonatype.central</groupId>
            <artifactId>central-publishing-maven-plugin</artifactId>
            <version>0.9.0</version>
            <extensions>false</extensions>
            <executions>
              <execution>
                <id>injected-central-publishing</id>
                <phase>none</phase>
              </execution>
            </executions>
            <configuration>
              <publishingServerId>skip</publishingServerId>
            </configuration>
          </plugin>
        </plugins>
      </build>
      <properties>
        <maven.deploy.skip>true</maven.deploy.skip>
        <maven.install.skip>true</maven.install.skip>
      </properties>
    </profile>

  </profiles>
</project>
