<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>cn.geoair.dependencies</groupId>
		<artifactId>geoair-dependencies</artifactId>
		<version>23.0.2-SNAPSHOT</version>
		<relativePath>../pom.xml</relativePath>
	</parent>

	<artifactId>geoair-dependencies-parent</artifactId>
	<name>geoair-dependencies-parent</name>
	<packaging>pom</packaging>
	<description>geoair-dependencies-parent</description>

	<properties>
		<geoair.version>${project.version}</geoair.version>
		<geoair.comp.version>${project.version}</geoair.comp.version>
		<skipTests>true</skipTests>
	</properties>

	<dependencyManagement>
		<dependencies>




		</dependencies>

	</dependencyManagement>



	<modules>
		<module>geoair-api-parent</module>
		<module>geoair-module-pom</module>
		<module>geoair-comp-parent</module>
		<module>geoair-project-parent</module>

		<module>geoair-spring-boot-starter-parent</module>
	</modules>


</project>
