package cn.geoair.comp.knife4j.ext.springdoc.auto;

import cn.geoair.comp.knife4j.ext.config.GirSwaggerApiConfig;

import cn.geoair.comp.knife4j.ext.model.ApiModelInfo;
import cn.geoair.comp.knife4j.ext.model.DocketInfo;
import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Contact;
import io.swagger.v3.oas.models.info.Info;
import org.springdoc.core.GroupedOpenApi;
import org.springframework.beans.BeansException;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ApplicationContextAware;
import org.springframework.context.annotation.Bean;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;


public class SpringDocApiRunner implements ApplicationContextAware {


    private GirSwaggerApiConfig apiConfig;


    /**
     * Spring自动注入ApplicationContext，并初始化配置属性
     */
    @Override
    public void setApplicationContext(ApplicationContext applicationContext) throws BeansException {
        // 初始化配置属性
        this.apiConfig = applicationContext.getBean(GirSwaggerApiConfig.class);

    }

    /**
     * 核心方法： 生成Docket
     */
    @Bean
    @ConditionalOnMissingBean(GroupedOpenApi.class)
    public Map<String, GroupedOpenApi> autoGenerateDockets() {
        List<DocketInfo> docketInfos = apiConfig.getDocketInfos();
        Map<String, GroupedOpenApi> docketMap = new LinkedHashMap<>();

        for (DocketInfo docketInfo : docketInfos) {
            GroupedOpenApi build = GroupedOpenApi.builder()
                    .group(docketInfo.getGroupName().replaceAll("[^a-zA-Z0-9]", "-")) // 分组名称（swagger-ui中可切换）
                    .packagesToScan(docketInfo.getBasePackage()) // 扫描的包
                    .build();
            docketMap.put("docket-" + docketInfo.getGroupName(), build);
        }
        return docketMap;
    }

    /**
     * 基础OpenAPI配置
     */
    @Bean
    @ConditionalOnMissingBean(OpenAPI.class)
    public OpenAPI customOpenAPI() {
        ApiModelInfo apiModelInfo1 = apiConfig.getApiModelInfo();
        Contact   contact = new Contact();
        contact.setName(apiModelInfo1.getAuthor());
        contact.setEmail("");
        contact.setUrl("");
        return new OpenAPI()
                .info(new Info()
                        .contact(contact)
                        .title(apiModelInfo1.getTitle())
                        .version(apiModelInfo1.getVersion())
                        .termsOfService(apiModelInfo1.getAuthor())
                        .description(apiModelInfo1.getDescription()));
    }
}
